import type { FoodNames } from "../catalog";

export const ar: FoodNames = {
  "pasta-dry": "معكرونة، نيئة|باستا|سباغيتي",
  "pasta-cooked": "معكرونة، مطبوخة|باستا|سباغيتي",
  "wholewheat-pasta-dry": "معكرونة قمح كامل، نيئة",
  "rice-dry": "أرز، نيء|أرز أبيض",
  "rice-cooked": "أرز، مطبوخ|أرز أبيض",
  "brown-rice-cooked": "أرز بني، مطبوخ",
  "bread-white": "خبز أبيض|خبز|توست",
  "bread-wholemeal": "خبز أسمر|خبز قمح كامل|خبز",
  rusks: "خبز محمص|بقسماط",
  crackers: "بسكويت مالح|كراكرز",
  oats: "رقائق الشوفان|شوفان",
  cornflakes: "رقائق الذرة|كورن فليكس|حبوب الإفطار",
  muesli: "موسلي|حبوب الإفطار|جرانولا",
  "couscous-cooked": "كسكس، مطبوخ",
  "quinoa-cooked": "كينوا، مطبوخة",
  "polenta-cooked": "بولنتا، مطبوخة|عصيدة الذرة",
  "potatoes-boiled": "بطاطس مسلوقة|بطاطا|بطاطس",
  "french-fries": "بطاطس مقلية|بطاطا مقلية",
  "pizza-margherita": "بيتزا مارغريتا|بيتزا",
  croissant: "كرواسون",
  "butter-cookies": "بسكويت بالزبدة|بسكويت|كوكيز",
  "chicken-breast-raw": "صدر دجاج، نيء|دجاج",
  "chicken-breast-cooked": "صدر دجاج، مطبوخ|دجاج|دجاج مشوي",
  "turkey-breast-raw": "صدر ديك رومي، نيء|ديك رومي",
  "beef-lean-raw": "لحم بقري قليل الدهن، نيء|ستيك|لحم بقري",
  "beef-ground-raw": "لحم بقري مفروم، نيء|لحم مفروم|برغر",
  "pork-loin-raw": "لحم خاصرة الخنزير، نيء|لحم خنزير",
  "pork-sausage-raw": "نقانق لحم الخنزير، نيئة|نقانق",
  "cooked-ham": "لحم خنزير مطبوخ (هام)|هام",
  "cured-ham": "لحم خنزير مقدد|بروشوتو|هام",
  bresaola: "بريزاولا|لحم بقري مجفف",
  salami: "سلامي",
  egg: "بيضة|بيض",
  "egg-white": "بياض البيض|بيض",
  "tuna-in-water": "تونة بالماء، مصفاة|تونة معلبة|تونة",
  "tuna-in-oil": "تونة بالزيت، مصفاة|تونة معلبة|تونة",
  "salmon-raw": "سلمون، نيء|سلمون",
  "cod-raw": "سمك القد، نيء|سمك",
  "shrimp-raw": "روبيان، نيء|جمبري|قريدس",
  tofu: "توفو صلب|توفو",
  "whey-protein": "بروتين مصل اللبن (واي)|بروتين بودرة|مخفوق البروتين",
  "yogurt-plain": "زبادي سادة|لبن زبادي|زبادي",
  "greek-yogurt-0": "زبادي يوناني خالي الدسم|زبادي يوناني|سكير",
  "greek-yogurt-full": "زبادي يوناني كامل الدسم|زبادي يوناني",
  mozzarella: "موزاريلا طازجة|موزاريلا|جبن",
  parmesan: "بارميزان|جبن مبشور|جبن",
  ricotta: "ريكوتا|جبن",
  cheddar: "شيدر|جبن",
  feta: "فيتا|جبن أبيض|جبن",
  "cottage-cheese": "جبن قريش|جبن كوخ|جبن",
  butter: "زبدة",
  "milk-whole": "حليب كامل الدسم|حليب",
  "milk-semi": "حليب قليل الدسم|حليب",
  "milk-skim": "حليب خالي الدسم|حليب",
  "chickpeas-cooked": "حمص حب، مطبوخ|حمص معلب",
  "chickpeas-dry": "حمص حب، مجفف",
  "lentils-cooked": "عدس، مطبوخ",
  "lentils-dry": "عدس، مجفف",
  "beans-cooked": "فاصوليا حمراء، مطبوخة|فاصوليا",
  peas: "بازلاء|بسلة",
  hummus: "حمص بالطحينة|حمص",
  tomato: "طماطم|بندورة",
  lettuce: "خس|سلطة",
  carrot: "جزر",
  zucchini: "كوسة|كوسا",
  broccoli: "بروكلي",
  spinach: "سبانخ",
  "bell-pepper": "فلفل حلو|فلفل رومي",
  onion: "بصل",
  cucumber: "خيار",
  eggplant: "باذنجان",
  mushrooms: "فطر|مشروم",
  "green-beans": "فاصوليا خضراء",
  cauliflower: "قرنبيط|زهرة",
  avocado: "أفوكادو",
  "sweet-corn": "ذرة حلوة|ذرة",
  "sweet-potato": "بطاطا حلوة",
  "tomato-sauce": "صلصة طماطم|طماطم مهروسة",
  apple: "تفاح|تفاحة",
  banana: "موز|موزة",
  orange: "برتقال|برتقالة",
  mandarin: "يوسفي|مندرين|كليمنتين",
  pear: "كمثرى|إجاص",
  peach: "خوخ|دراق",
  apricot: "مشمش",
  kiwi: "كيوي",
  strawberries: "فراولة",
  blueberries: "توت أزرق|عنب الثعلب",
  cherries: "كرز",
  grapes: "عنب",
  watermelon: "بطيخ|بطيخ أحمر",
  melon: "شمام|بطيخ أصفر",
  pineapple: "أناناس",
  "dates-dried": "تمر",
  raisins: "زبيب",
  almonds: "لوز|مكسرات",
  walnuts: "جوز|عين الجمل|مكسرات",
  hazelnuts: "بندق|مكسرات",
  peanuts: "فول سوداني|مكسرات",
  pistachios: "فستق حلبي|فستق|مكسرات",
  cashews: "كاجو|مكسرات",
  "peanut-butter": "زبدة الفول السوداني",
  "chia-seeds": "بذور الشيا|شيا",
  "olive-oil": "زيت الزيتون|زيت",
  mayonnaise: "مايونيز",
  ketchup: "كاتشب",
  pesto: "صلصة البيستو|بيستو",
  honey: "عسل",
  sugar: "سكر",
  jam: "مربى",
  "dark-chocolate": "شوكولاتة داكنة|شوكولاتة",
  "milk-chocolate": "شوكولاتة بالحليب|شوكولاتة",
  "ice-cream": "آيس كريم|بوظة|مثلجات",
  "potato-chips": "رقائق البطاطس|شيبس",
  "orange-juice": "عصير برتقال|عصير",
  cola: "كولا|مشروب غازي",
  coffee: "قهوة سوداء|قهوة|إسبريسو",
  beer: "بيرة",
  wine: "نبيذ|نبيذ أحمر|نبيذ أبيض",
};
