import type { FoodNames } from "../catalog";

export const de: FoodNames = {
  "pasta-dry": "Nudeln, roh|Pasta|Spaghetti|Teigwaren",
  "pasta-cooked": "Nudeln, gekocht|Pasta|Spaghetti",
  "wholewheat-pasta-dry": "Vollkornnudeln, roh|Vollkornpasta",
  "rice-dry": "Reis, roh|weißer Reis",
  "rice-cooked": "Reis, gekocht|weißer Reis",
  "brown-rice-cooked": "Vollkornreis, gekocht|Naturreis",
  "bread-white": "Weißbrot|Brot|Toast",
  "bread-wholemeal": "Vollkornbrot|Brot",
  rusks: "Zwieback",
  crackers: "Cracker",
  oats: "Haferflocken|Hafer|Porridge",
  cornflakes: "Cornflakes|Müsli|Cerealien",
  muesli: "Müsli|Granola",
  "couscous-cooked": "Couscous, gekocht",
  "quinoa-cooked": "Quinoa, gekocht",
  "polenta-cooked": "Polenta, gekocht",
  "potatoes-boiled": "Kartoffeln, gekocht|Salzkartoffeln|Kartoffel",
  "french-fries": "Pommes frites|Pommes",
  "pizza-margherita": "Pizza Margherita|Pizza",
  croissant: "Croissant|Hörnchen",
  "butter-cookies": "Butterkekse|Kekse",
  "chicken-breast-raw": "Hähnchenbrust, roh|Hähnchen|Huhn",
  "chicken-breast-cooked": "Hähnchenbrust, gegart|Hähnchen|gegrilltes Hähnchen",
  "turkey-breast-raw": "Putenbrust, roh|Pute",
  "beef-lean-raw": "Mageres Rindfleisch, roh|Steak|Rind",
  "beef-ground-raw": "Rinderhackfleisch, roh|Hackfleisch|Burger",
  "pork-loin-raw": "Schweinelende, roh|Schweinekotelett|Schwein",
  "pork-sausage-raw": "Bratwurst, roh|Wurst",
  "cooked-ham": "Kochschinken|Schinken",
  "cured-ham": "Rohschinken|Parmaschinken|Schinken",
  bresaola: "Bresaola|Bündnerfleisch",
  salami: "Salami",
  egg: "Ei|Eier",
  "egg-white": "Eiweiß|Eiklar|Eier",
  "tuna-in-water": "Thunfisch im eigenen Saft, abgetropft|Thunfisch",
  "tuna-in-oil": "Thunfisch in Öl, abgetropft|Thunfisch",
  "salmon-raw": "Lachs, roh|Lachs",
  "cod-raw": "Kabeljau, roh|Fisch",
  "shrimp-raw": "Garnelen, roh|Shrimps",
  tofu: "Tofu, fest|Tofu",
  "whey-protein": "Whey-Proteinpulver|Proteinpulver|Shake",
  "yogurt-plain": "Naturjoghurt|Joghurt",
  "greek-yogurt-0": "Griechischer Joghurt 0 %|Magerjoghurt|Skyr",
  "greek-yogurt-full": "Griechischer Joghurt, vollfett|griechischer Joghurt",
  mozzarella: "Mozzarella, frisch|Mozzarella|Käse",
  parmesan: "Parmesan|Reibekäse|Käse",
  ricotta: "Ricotta|Käse",
  cheddar: "Cheddar|Käse",
  feta: "Feta|Schafskäse|Käse",
  "cottage-cheese": "Hüttenkäse|Körniger Frischkäse|Käse",
  butter: "Butter",
  "milk-whole": "Vollmilch|Milch",
  "milk-semi": "Fettarme Milch|Milch",
  "milk-skim": "Magermilch|Milch",
  "chickpeas-cooked": "Kichererbsen, gekocht|Kichererbsen aus der Dose",
  "chickpeas-dry": "Kichererbsen, getrocknet",
  "lentils-cooked": "Linsen, gekocht",
  "lentils-dry": "Linsen, getrocknet",
  "beans-cooked": "Kidneybohnen, gekocht|Bohnen",
  peas: "Erbsen",
  hummus: "Hummus",
  tomato: "Tomate|Tomaten",
  lettuce: "Kopfsalat|Salat",
  carrot: "Karotte|Möhre|Karotten",
  zucchini: "Zucchini",
  broccoli: "Brokkoli",
  spinach: "Spinat",
  "bell-pepper": "Paprika",
  onion: "Zwiebel",
  cucumber: "Gurke",
  eggplant: "Aubergine",
  mushrooms: "Champignons|Pilze",
  "green-beans": "Grüne Bohnen",
  cauliflower: "Blumenkohl",
  avocado: "Avocado",
  "sweet-corn": "Mais, süß|Mais",
  "sweet-potato": "Süßkartoffel",
  "tomato-sauce": "Passierte Tomaten|Tomatensoße|Passata",
  apple: "Apfel",
  banana: "Banane",
  orange: "Orange|Apfelsine",
  mandarin: "Mandarine|Clementine",
  pear: "Birne",
  peach: "Pfirsich",
  apricot: "Aprikose",
  kiwi: "Kiwi",
  strawberries: "Erdbeeren",
  blueberries: "Heidelbeeren|Blaubeeren",
  cherries: "Kirschen",
  grapes: "Weintrauben|Trauben",
  watermelon: "Wassermelone",
  melon: "Honigmelone|Melone",
  pineapple: "Ananas",
  "dates-dried": "Datteln, getrocknet|Datteln",
  raisins: "Rosinen",
  almonds: "Mandeln|Nüsse",
  walnuts: "Walnüsse|Nüsse",
  hazelnuts: "Haselnüsse|Nüsse",
  peanuts: "Erdnüsse|Nüsse",
  pistachios: "Pistazien|Nüsse",
  cashews: "Cashewkerne|Nüsse",
  "peanut-butter": "Erdnussbutter",
  "chia-seeds": "Chiasamen|Samen",
  "olive-oil": "Olivenöl|Öl",
  mayonnaise: "Mayonnaise|Mayo",
  ketchup: "Ketchup",
  pesto: "Pesto",
  honey: "Honig",
  sugar: "Zucker",
  jam: "Marmelade|Konfitüre",
  "dark-chocolate": "Zartbitterschokolade|Schokolade",
  "milk-chocolate": "Milchschokolade|Schokolade",
  "ice-cream": "Eiscreme|Eis",
  "potato-chips": "Kartoffelchips|Chips",
  "orange-juice": "Orangensaft|Saft",
  cola: "Cola|Limonade|Softdrink",
  coffee: "Kaffee, schwarz|Kaffee|Espresso",
  beer: "Bier",
  wine: "Wein|Rotwein|Weißwein",
};
