import type { FoodNames } from "../catalog";

export const en: FoodNames = {
  "pasta-dry": "Pasta, dry|spaghetti|penne|macaroni",
  "pasta-cooked": "Pasta, cooked|spaghetti|penne|macaroni",
  "wholewheat-pasta-dry": "Wholewheat pasta, dry|whole wheat spaghetti",
  "rice-dry": "Rice, dry|white rice",
  "rice-cooked": "Rice, cooked|white rice|boiled rice",
  "brown-rice-cooked": "Brown rice, cooked|wholegrain rice",
  "bread-white": "White bread|bread|toast",
  "bread-wholemeal": "Wholemeal bread|whole wheat bread|brown bread",
  rusks: "Rusks|crispbread|toasted bread",
  crackers: "Crackers",
  oats: "Oats|oatmeal|porridge oats|rolled oats",
  cornflakes: "Cornflakes|cereal",
  muesli: "Muesli|cereal|granola",
  "couscous-cooked": "Couscous, cooked",
  "quinoa-cooked": "Quinoa, cooked",
  "polenta-cooked": "Polenta, cooked|grits|cornmeal",
  "potatoes-boiled": "Potatoes, boiled|potato",
  "french-fries": "French fries|chips|fries",
  "pizza-margherita": "Pizza margherita|pizza|cheese pizza",
  croissant: "Croissant|pastry",
  "butter-cookies": "Butter cookies|biscuits|cookies",
  "chicken-breast-raw": "Chicken breast, raw|chicken",
  "chicken-breast-cooked": "Chicken breast, cooked|chicken|grilled chicken",
  "turkey-breast-raw": "Turkey breast, raw|turkey",
  "beef-lean-raw": "Lean beef, raw|steak|beef",
  "beef-ground-raw": "Ground beef, raw|minced beef|mince|burger",
  "pork-loin-raw": "Pork loin, raw|pork chop|pork",
  "pork-sausage-raw": "Pork sausage, raw|sausage",
  "cooked-ham": "Cooked ham|ham",
  "cured-ham": "Cured ham|prosciutto|ham",
  bresaola: "Bresaola|cured beef",
  salami: "Salami",
  egg: "Egg|eggs",
  "egg-white": "Egg white|eggs",
  "tuna-in-water": "Tuna in water, drained|canned tuna|tuna",
  "tuna-in-oil": "Tuna in oil, drained|canned tuna|tuna",
  "salmon-raw": "Salmon, raw|salmon",
  "cod-raw": "Cod, raw|fish",
  "shrimp-raw": "Shrimp, raw|prawns",
  tofu: "Tofu, firm|tofu",
  "whey-protein": "Whey protein powder|protein powder|shake",
  "yogurt-plain": "Plain yogurt|yoghurt",
  "greek-yogurt-0": "Greek yogurt, 0% fat|fat-free greek yogurt|skyr",
  "greek-yogurt-full": "Greek yogurt, full fat|greek yoghurt",
  mozzarella: "Mozzarella, fresh|cheese",
  parmesan: "Parmesan|parmigiano|cheese",
  ricotta: "Ricotta|cheese",
  cheddar: "Cheddar|cheese",
  feta: "Feta|cheese",
  "cottage-cheese": "Cottage cheese|cheese",
  butter: "Butter",
  "milk-whole": "Whole milk|milk",
  "milk-semi": "Semi-skimmed milk|milk|low-fat milk",
  "milk-skim": "Skimmed milk|milk|skim milk",
  "chickpeas-cooked": "Chickpeas, cooked|canned chickpeas|garbanzo beans",
  "chickpeas-dry": "Chickpeas, dry|garbanzo beans",
  "lentils-cooked": "Lentils, cooked|canned lentils",
  "lentils-dry": "Lentils, dry",
  "beans-cooked": "Beans, cooked|kidney beans|canned beans",
  peas: "Peas|green peas",
  hummus: "Hummus",
  tomato: "Tomato|tomatoes",
  lettuce: "Lettuce|salad",
  carrot: "Carrot|carrots",
  zucchini: "Zucchini|courgette",
  broccoli: "Broccoli",
  spinach: "Spinach",
  "bell-pepper": "Bell pepper|pepper",
  onion: "Onion",
  cucumber: "Cucumber",
  eggplant: "Eggplant|aubergine",
  mushrooms: "Mushrooms",
  "green-beans": "Green beans",
  cauliflower: "Cauliflower",
  avocado: "Avocado",
  "sweet-corn": "Sweet corn|corn",
  "sweet-potato": "Sweet potato",
  "tomato-sauce": "Tomato sauce|passata",
  apple: "Apple",
  banana: "Banana",
  orange: "Orange",
  mandarin: "Mandarin|tangerine|clementine",
  pear: "Pear",
  peach: "Peach",
  apricot: "Apricot",
  kiwi: "Kiwi",
  strawberries: "Strawberries",
  blueberries: "Blueberries",
  cherries: "Cherries",
  grapes: "Grapes",
  watermelon: "Watermelon",
  melon: "Melon|cantaloupe",
  pineapple: "Pineapple",
  "dates-dried": "Dates, dried",
  raisins: "Raisins",
  almonds: "Almonds|nuts",
  walnuts: "Walnuts|nuts",
  hazelnuts: "Hazelnuts|nuts",
  peanuts: "Peanuts|nuts",
  pistachios: "Pistachios|nuts",
  cashews: "Cashews|nuts",
  "peanut-butter": "Peanut butter",
  "chia-seeds": "Chia seeds|seeds",
  "olive-oil": "Olive oil|oil",
  mayonnaise: "Mayonnaise|mayo",
  ketchup: "Ketchup",
  pesto: "Pesto",
  honey: "Honey",
  sugar: "Sugar",
  jam: "Jam|jelly",
  "dark-chocolate": "Dark chocolate|chocolate",
  "milk-chocolate": "Milk chocolate|chocolate",
  "ice-cream": "Ice cream|gelato",
  "potato-chips": "Potato chips|crisps",
  "orange-juice": "Orange juice|juice",
  cola: "Cola|soda|soft drink",
  coffee: "Coffee, black|espresso|coffee",
  beer: "Beer",
  wine: "Wine|red wine|white wine",
};
