import type { FoodNames } from "../catalog";

export const es: FoodNames = {
  "pasta-dry": "Pasta, cruda|espaguetis|macarrones",
  "pasta-cooked": "Pasta, cocida|espaguetis|macarrones",
  "wholewheat-pasta-dry": "Pasta integral, cruda",
  "rice-dry": "Arroz, crudo|arroz blanco",
  "rice-cooked": "Arroz, cocido|arroz blanco|arroz hervido",
  "brown-rice-cooked": "Arroz integral, cocido",
  "bread-white": "Pan blanco|pan|pan de molde",
  "bread-wholemeal": "Pan integral|pan",
  rusks: "Biscotes|pan tostado",
  crackers: "Galletas saladas|crackers",
  oats: "Copos de avena|avena|porridge",
  cornflakes: "Copos de maíz|cereales|corn flakes",
  muesli: "Muesli|cereales|granola",
  "couscous-cooked": "Cuscús, cocido",
  "quinoa-cooked": "Quinoa, cocida",
  "polenta-cooked": "Polenta, cocida",
  "potatoes-boiled": "Patatas hervidas|papas|patata",
  "french-fries": "Patatas fritas|papas fritas",
  "pizza-margherita": "Pizza margarita|pizza",
  croissant: "Cruasán|croissant|bollería",
  "butter-cookies": "Galletas de mantequilla|galletas",
  "chicken-breast-raw": "Pechuga de pollo, cruda|pollo",
  "chicken-breast-cooked": "Pechuga de pollo, cocinada|pollo|pollo a la plancha",
  "turkey-breast-raw": "Pechuga de pavo, cruda|pavo",
  "beef-lean-raw": "Ternera magra, cruda|filete|ternera|carne de res",
  "beef-ground-raw": "Carne picada de ternera, cruda|carne molida|hamburguesa",
  "pork-loin-raw": "Lomo de cerdo, crudo|cerdo",
  "pork-sausage-raw": "Salchicha de cerdo, cruda|salchicha",
  "cooked-ham": "Jamón cocido|jamón york|jamón",
  "cured-ham": "Jamón curado|jamón serrano|jamón",
  bresaola: "Bresaola|cecina",
  salami: "Salami|salchichón",
  egg: "Huevo|huevos",
  "egg-white": "Clara de huevo|huevos",
  "tuna-in-water": "Atún al natural, escurrido|atún en lata|atún",
  "tuna-in-oil": "Atún en aceite, escurrido|atún en lata|atún",
  "salmon-raw": "Salmón, crudo|salmón",
  "cod-raw": "Bacalao, crudo|pescado",
  "shrimp-raw": "Gambas, crudas|camarones|langostinos",
  tofu: "Tofu",
  "whey-protein": "Proteína whey en polvo|proteína en polvo|batido",
  "yogurt-plain": "Yogur natural|yogur",
  "greek-yogurt-0": "Yogur griego 0%|yogur griego desnatado|skyr",
  "greek-yogurt-full": "Yogur griego entero|yogur griego",
  mozzarella: "Mozzarella fresca|mozzarella|queso",
  parmesan: "Parmesano|queso rallado|queso",
  ricotta: "Ricota|requesón|queso",
  cheddar: "Cheddar|queso",
  feta: "Feta|queso",
  "cottage-cheese": "Queso cottage|requesón|queso",
  butter: "Mantequilla",
  "milk-whole": "Leche entera|leche",
  "milk-semi": "Leche semidesnatada|leche",
  "milk-skim": "Leche desnatada|leche",
  "chickpeas-cooked": "Garbanzos, cocidos|garbanzos de bote",
  "chickpeas-dry": "Garbanzos, secos",
  "lentils-cooked": "Lentejas, cocidas|lentejas de bote",
  "lentils-dry": "Lentejas, secas",
  "beans-cooked": "Alubias, cocidas|frijoles|judías",
  peas: "Guisantes|arvejas",
  hummus: "Hummus",
  tomato: "Tomate|tomates",
  lettuce: "Lechuga|ensalada",
  carrot: "Zanahoria|zanahorias",
  zucchini: "Calabacín",
  broccoli: "Brócoli",
  spinach: "Espinacas",
  "bell-pepper": "Pimiento",
  onion: "Cebolla",
  cucumber: "Pepino",
  eggplant: "Berenjena",
  mushrooms: "Champiñones|setas",
  "green-beans": "Judías verdes|ejotes",
  cauliflower: "Coliflor",
  avocado: "Aguacate|palta",
  "sweet-corn": "Maíz dulce|maíz",
  "sweet-potato": "Boniato|batata|camote",
  "tomato-sauce": "Tomate triturado|salsa de tomate|passata",
  apple: "Manzana",
  banana: "Plátano|banana",
  orange: "Naranja",
  mandarin: "Mandarina|clementina",
  pear: "Pera",
  peach: "Melocotón|durazno",
  apricot: "Albaricoque|damasco",
  kiwi: "Kiwi",
  strawberries: "Fresas|frutillas",
  blueberries: "Arándanos",
  cherries: "Cerezas",
  grapes: "Uvas",
  watermelon: "Sandía",
  melon: "Melón",
  pineapple: "Piña|ananá",
  "dates-dried": "Dátiles secos|dátiles",
  raisins: "Pasas|uvas pasas",
  almonds: "Almendras|frutos secos",
  walnuts: "Nueces|frutos secos",
  hazelnuts: "Avellanas|frutos secos",
  peanuts: "Cacahuetes|maní|frutos secos",
  pistachios: "Pistachos|frutos secos",
  cashews: "Anacardos|castañas de cajú|frutos secos",
  "peanut-butter": "Crema de cacahuete|mantequilla de maní",
  "chia-seeds": "Semillas de chía|semillas",
  "olive-oil": "Aceite de oliva|aceite",
  mayonnaise: "Mayonesa",
  ketchup: "Kétchup|ketchup",
  pesto: "Pesto",
  honey: "Miel",
  sugar: "Azúcar",
  jam: "Mermelada",
  "dark-chocolate": "Chocolate negro|chocolate",
  "milk-chocolate": "Chocolate con leche|chocolate",
  "ice-cream": "Helado",
  "potato-chips": "Patatas fritas de bolsa|papas fritas de bolsa|chips",
  "orange-juice": "Zumo de naranja|jugo de naranja|zumo",
  cola: "Refresco de cola|cola|refresco",
  coffee: "Café solo|café|espresso",
  beer: "Cerveza",
  wine: "Vino|vino tinto|vino blanco",
};
