import type { FoodNames } from "../catalog";

export const fr: FoodNames = {
  "pasta-dry": "Pâtes, crues|spaghetti|penne|macaronis",
  "pasta-cooked": "Pâtes, cuites|spaghetti|penne|macaronis",
  "wholewheat-pasta-dry": "Pâtes complètes, crues",
  "rice-dry": "Riz, cru|riz blanc",
  "rice-cooked": "Riz, cuit|riz blanc",
  "brown-rice-cooked": "Riz complet, cuit",
  "bread-white": "Pain blanc|pain|baguette|pain de mie",
  "bread-wholemeal": "Pain complet|pain",
  rusks: "Biscottes",
  crackers: "Crackers|biscuits salés",
  oats: "Flocons d'avoine|avoine|porridge",
  cornflakes: "Corn flakes|céréales",
  muesli: "Muesli|céréales|granola",
  "couscous-cooked": "Semoule de couscous, cuite|couscous",
  "quinoa-cooked": "Quinoa, cuit",
  "polenta-cooked": "Polenta, cuite",
  "potatoes-boiled": "Pommes de terre, cuites à l'eau|pomme de terre|patates",
  "french-fries": "Frites",
  "pizza-margherita": "Pizza margherita|pizza",
  croissant: "Croissant|viennoiserie",
  "butter-cookies": "Biscuits au beurre|sablés|biscuits",
  "chicken-breast-raw": "Blanc de poulet, cru|poulet",
  "chicken-breast-cooked": "Blanc de poulet, cuit|poulet|poulet grillé",
  "turkey-breast-raw": "Blanc de dinde, cru|dinde",
  "beef-lean-raw": "Bœuf maigre, cru|steak|bœuf",
  "beef-ground-raw": "Bœuf haché, cru|steak haché|viande hachée",
  "pork-loin-raw": "Filet de porc, cru|côte de porc|porc",
  "pork-sausage-raw": "Saucisse de porc, crue|saucisse",
  "cooked-ham": "Jambon blanc|jambon cuit|jambon",
  "cured-ham": "Jambon cru|jambon de Parme|jambon",
  bresaola: "Bresaola|viande séchée",
  salami: "Salami|saucisson",
  egg: "Œuf|œufs|oeuf",
  "egg-white": "Blanc d'œuf|blanc d'oeuf|œufs",
  "tuna-in-water": "Thon au naturel, égoutté|thon en boîte|thon",
  "tuna-in-oil": "Thon à l'huile, égoutté|thon en boîte|thon",
  "salmon-raw": "Saumon, cru|saumon",
  "cod-raw": "Cabillaud, cru|morue|poisson",
  "shrimp-raw": "Crevettes, crues|crevettes",
  tofu: "Tofu ferme|tofu",
  "whey-protein": "Protéine whey en poudre|protéine en poudre|shake",
  "yogurt-plain": "Yaourt nature|yaourt|yogourt",
  "greek-yogurt-0": "Yaourt grec 0 %|yaourt grec allégé|skyr",
  "greek-yogurt-full": "Yaourt grec entier|yaourt grec",
  mozzarella: "Mozzarella fraîche|mozzarella|fromage",
  parmesan: "Parmesan|fromage râpé|fromage",
  ricotta: "Ricotta|fromage",
  cheddar: "Cheddar|fromage",
  feta: "Feta|fromage",
  "cottage-cheese": "Cottage cheese|fromage blanc|fromage",
  butter: "Beurre",
  "milk-whole": "Lait entier|lait",
  "milk-semi": "Lait demi-écrémé|lait",
  "milk-skim": "Lait écrémé|lait",
  "chickpeas-cooked": "Pois chiches, cuits|pois chiches en conserve",
  "chickpeas-dry": "Pois chiches, secs",
  "lentils-cooked": "Lentilles, cuites",
  "lentils-dry": "Lentilles, sèches",
  "beans-cooked": "Haricots rouges, cuits|haricots",
  peas: "Petits pois",
  hummus: "Houmous|hummus",
  tomato: "Tomate|tomates",
  lettuce: "Laitue|salade",
  carrot: "Carotte|carottes",
  zucchini: "Courgette",
  broccoli: "Brocoli",
  spinach: "Épinards",
  "bell-pepper": "Poivron",
  onion: "Oignon",
  cucumber: "Concombre",
  eggplant: "Aubergine",
  mushrooms: "Champignons",
  "green-beans": "Haricots verts",
  cauliflower: "Chou-fleur",
  avocado: "Avocat",
  "sweet-corn": "Maïs doux|maïs",
  "sweet-potato": "Patate douce",
  "tomato-sauce": "Coulis de tomate|sauce tomate|passata",
  apple: "Pomme",
  banana: "Banane",
  orange: "Orange",
  mandarin: "Mandarine|clémentine",
  pear: "Poire",
  peach: "Pêche",
  apricot: "Abricot",
  kiwi: "Kiwi",
  strawberries: "Fraises",
  blueberries: "Myrtilles",
  cherries: "Cerises",
  grapes: "Raisin",
  watermelon: "Pastèque",
  melon: "Melon",
  pineapple: "Ananas",
  "dates-dried": "Dattes séchées|dattes",
  raisins: "Raisins secs",
  almonds: "Amandes|fruits secs",
  walnuts: "Noix|fruits secs",
  hazelnuts: "Noisettes|fruits secs",
  peanuts: "Cacahuètes|arachides|fruits secs",
  pistachios: "Pistaches|fruits secs",
  cashews: "Noix de cajou|fruits secs",
  "peanut-butter": "Beurre de cacahuète",
  "chia-seeds": "Graines de chia|graines",
  "olive-oil": "Huile d'olive|huile",
  mayonnaise: "Mayonnaise",
  ketchup: "Ketchup",
  pesto: "Pesto",
  honey: "Miel",
  sugar: "Sucre",
  jam: "Confiture",
  "dark-chocolate": "Chocolat noir|chocolat",
  "milk-chocolate": "Chocolat au lait|chocolat",
  "ice-cream": "Glace|crème glacée",
  "potato-chips": "Chips",
  "orange-juice": "Jus d'orange|jus",
  cola: "Cola|soda",
  coffee: "Café noir|café|expresso",
  beer: "Bière",
  wine: "Vin|vin rouge|vin blanc",
};
