import type { FoodNames } from "../catalog";

export const he: FoodNames = {
  "pasta-dry": "פסטה, לא מבושלת|ספגטי|מקרוני",
  "pasta-cooked": "פסטה, מבושלת|ספגטי|מקרוני",
  "wholewheat-pasta-dry": "פסטה מקמח מלא, לא מבושלת",
  "rice-dry": "אורז, לא מבושל|אורז לבן",
  "rice-cooked": "אורז, מבושל|אורז לבן",
  "brown-rice-cooked": "אורז מלא, מבושל",
  "bread-white": "לחם לבן|לחם|טוסט",
  "bread-wholemeal": "לחם מקמח מלא|לחם",
  rusks: "צנימים|פריכיות לחם",
  crackers: "קרקרים",
  oats: "פתיתי שיבולת שועל|שיבולת שועל|דייסה",
  cornflakes: "קורנפלקס|דגני בוקר",
  muesli: "מוזלי|דגני בוקר|גרנולה",
  "couscous-cooked": "קוסקוס, מבושל",
  "quinoa-cooked": "קינואה, מבושלת",
  "polenta-cooked": "פולנטה, מבושלת",
  "potatoes-boiled": "תפוחי אדמה מבושלים|תפוח אדמה",
  "french-fries": "צ'יפס|טוגנים",
  "pizza-margherita": "פיצה מרגריטה|פיצה",
  croissant: "קרואסון",
  "butter-cookies": "עוגיות חמאה|עוגיות",
  "chicken-breast-raw": "חזה עוף, לא מבושל|עוף",
  "chicken-breast-cooked": "חזה עוף, מבושל|עוף|חזה עוף צלוי",
  "turkey-breast-raw": "חזה הודו, לא מבושל|הודו",
  "beef-lean-raw": "בקר רזה, לא מבושל|סטייק|בקר",
  "beef-ground-raw": "בשר בקר טחון, לא מבושל|בשר טחון|המבורגר",
  "pork-loin-raw": "מותן חזיר, לא מבושל|חזיר",
  "pork-sausage-raw": "נקניקיית חזיר, לא מבושלת|נקניקייה",
  "cooked-ham": "נקניק חזיר מבושל (ג'מבון)|ג'מבון",
  "cured-ham": "חזיר מיובש|פרושוטו",
  bresaola: "ברזאולה|בקר מיובש",
  salami: "סלמי",
  egg: "ביצה|ביצים",
  "egg-white": "חלבון ביצה|ביצים",
  "tuna-in-water": "טונה במים, מסוננת|טונה בקופסה|טונה",
  "tuna-in-oil": "טונה בשמן, מסוננת|טונה בקופסה|טונה",
  "salmon-raw": "סלמון, לא מבושל|סלמון",
  "cod-raw": "בקלה, לא מבושלת|דג",
  "shrimp-raw": "שרימפס, לא מבושלים|שרימפס",
  tofu: "טופו קשה|טופו",
  "whey-protein": "אבקת חלבון מי גבינה|אבקת חלבון|שייק חלבון",
  "yogurt-plain": "יוגורט טבעי|יוגורט",
  "greek-yogurt-0": "יוגורט יווני 0%|סקייר",
  "greek-yogurt-full": "יוגורט יווני מלא|יוגורט יווני",
  mozzarella: "מוצרלה טרייה|מוצרלה|גבינה",
  parmesan: "פרמזן|גבינה מגוררת|גבינה",
  ricotta: "ריקוטה|גבינה",
  cheddar: "צ'דר|גבינה צהובה|גבינה",
  feta: "פטה|גבינה בולגרית|גבינה",
  "cottage-cheese": "קוטג'|גבינה",
  butter: "חמאה",
  "milk-whole": "חלב 3%|חלב",
  "milk-semi": "חלב 1%|חלב דל שומן|חלב",
  "milk-skim": "חלב רזה|חלב",
  "chickpeas-cooked": "גרגרי חומוס, מבושלים|חומוס גרגרים",
  "chickpeas-dry": "גרגרי חומוס, יבשים",
  "lentils-cooked": "עדשים, מבושלות",
  "lentils-dry": "עדשים, יבשות",
  "beans-cooked": "שעועית אדומה, מבושלת|שעועית",
  peas: "אפונה",
  hummus: "חומוס (ממרח)|חומוס",
  tomato: "עגבנייה|עגבניות",
  lettuce: "חסה|סלט",
  carrot: "גזר",
  zucchini: "קישוא|זוקיני",
  broccoli: "ברוקולי",
  spinach: "תרד",
  "bell-pepper": "פלפל|גמבה",
  onion: "בצל",
  cucumber: "מלפפון",
  eggplant: "חציל",
  mushrooms: "פטריות|שמפיניון",
  "green-beans": "שעועית ירוקה",
  cauliflower: "כרובית",
  avocado: "אבוקדו",
  "sweet-corn": "תירס מתוק|תירס",
  "sweet-potato": "בטטה",
  "tomato-sauce": "רסק עגבניות|רוטב עגבניות",
  apple: "תפוח",
  banana: "בננה",
  orange: "תפוז",
  mandarin: "קלמנטינה|מנדרינה",
  pear: "אגס",
  peach: "אפרסק",
  apricot: "משמש",
  kiwi: "קיווי",
  strawberries: "תותים|תות",
  blueberries: "אוכמניות",
  cherries: "דובדבנים",
  grapes: "ענבים",
  watermelon: "אבטיח",
  melon: "מלון",
  pineapple: "אננס",
  "dates-dried": "תמרים",
  raisins: "צימוקים",
  almonds: "שקדים|אגוזים",
  walnuts: "אגוזי מלך|אגוזים",
  hazelnuts: "אגוזי לוז|אגוזים",
  peanuts: "בוטנים",
  pistachios: "פיסטוקים|אגוזים",
  cashews: "קשיו|אגוזים",
  "peanut-butter": "חמאת בוטנים",
  "chia-seeds": "זרעי צ'יה|צ'יה",
  "olive-oil": "שמן זית|שמן",
  mayonnaise: "מיונז",
  ketchup: "קטשופ",
  pesto: "פסטו",
  honey: "דבש",
  sugar: "סוכר",
  jam: "ריבה",
  "dark-chocolate": "שוקולד מריר|שוקולד",
  "milk-chocolate": "שוקולד חלב|שוקולד",
  "ice-cream": "גלידה",
  "potato-chips": "צ'יפס תפוחי אדמה (חטיף)|חטיף צ'יפס",
  "orange-juice": "מיץ תפוזים|מיץ",
  cola: "קולה|משקה מוגז",
  coffee: "קפה שחור|קפה|אספרסו",
  beer: "בירה",
  wine: "יין|יין אדום|יין לבן",
};
