import type { FoodNames } from "../catalog";

export const it: FoodNames = {
  "pasta-dry": "Pasta, cruda|spaghetti|penne|maccheroni|pasta secca",
  "pasta-cooked": "Pasta, cotta|spaghetti|penne|maccheroni",
  "wholewheat-pasta-dry": "Pasta integrale, cruda|spaghetti integrali",
  "rice-dry": "Riso, crudo|riso bianco",
  "rice-cooked": "Riso, cotto|riso bianco|riso bollito",
  "brown-rice-cooked": "Riso integrale, cotto",
  "bread-white": "Pane bianco|pane|pane comune|pancarré",
  "bread-wholemeal": "Pane integrale|pane",
  rusks: "Fette biscottate",
  crackers: "Cracker|crackers",
  oats: "Fiocchi d'avena|avena|porridge",
  cornflakes: "Corn flakes|cereali",
  muesli: "Muesli|cereali|granola",
  "couscous-cooked": "Cous cous, cotto|couscous",
  "quinoa-cooked": "Quinoa, cotta",
  "polenta-cooked": "Polenta, cotta",
  "potatoes-boiled": "Patate lesse|patate|patata",
  "french-fries": "Patatine fritte|patate fritte",
  "pizza-margherita": "Pizza margherita|pizza",
  croissant: "Cornetto|brioche|croissant",
  "butter-cookies": "Biscotti al burro|biscotti|frollini",
  "chicken-breast-raw": "Petto di pollo, crudo|pollo",
  "chicken-breast-cooked": "Petto di pollo, cotto|pollo|pollo alla griglia",
  "turkey-breast-raw": "Petto di tacchino, crudo|tacchino",
  "beef-lean-raw": "Manzo magro, crudo|bistecca|manzo|carne rossa",
  "beef-ground-raw": "Macinato di manzo, crudo|carne macinata|hamburger",
  "pork-loin-raw": "Lonza di maiale, cruda|braciola|maiale",
  "pork-sausage-raw": "Salsiccia di maiale, cruda|salsiccia",
  "cooked-ham": "Prosciutto cotto|prosciutto",
  "cured-ham": "Prosciutto crudo|prosciutto",
  bresaola: "Bresaola",
  salami: "Salame",
  egg: "Uovo|uova",
  "egg-white": "Albume|chiara d'uovo|uova",
  "tuna-in-water": "Tonno al naturale, sgocciolato|tonno in scatola|tonno",
  "tuna-in-oil": "Tonno sott'olio, sgocciolato|tonno in scatola|tonno",
  "salmon-raw": "Salmone, crudo|salmone",
  "cod-raw": "Merluzzo, crudo|pesce",
  "shrimp-raw": "Gamberi, crudi|gamberetti",
  tofu: "Tofu",
  "whey-protein": "Proteine whey in polvere|proteine in polvere|frullato proteico",
  "yogurt-plain": "Yogurt bianco|yogurt intero",
  "greek-yogurt-0": "Yogurt greco 0%|yogurt greco magro|skyr",
  "greek-yogurt-full": "Yogurt greco intero|yogurt greco",
  mozzarella: "Mozzarella|fior di latte|formaggio",
  parmesan: "Parmigiano|grana|formaggio grattugiato",
  ricotta: "Ricotta|formaggio",
  cheddar: "Cheddar|formaggio",
  feta: "Feta|formaggio",
  "cottage-cheese": "Fiocchi di latte|cottage cheese|formaggio",
  butter: "Burro",
  "milk-whole": "Latte intero|latte",
  "milk-semi": "Latte parzialmente scremato|latte",
  "milk-skim": "Latte scremato|latte",
  "chickpeas-cooked": "Ceci, cotti|ceci in scatola",
  "chickpeas-dry": "Ceci, secchi",
  "lentils-cooked": "Lenticchie, cotte|lenticchie in scatola",
  "lentils-dry": "Lenticchie, secche",
  "beans-cooked": "Fagioli, cotti|fagioli in scatola|borlotti|cannellini",
  peas: "Piselli",
  hummus: "Hummus",
  tomato: "Pomodoro|pomodori",
  lettuce: "Lattuga|insalata",
  carrot: "Carota|carote",
  zucchini: "Zucchina|zucchine",
  broccoli: "Broccoli",
  spinach: "Spinaci",
  "bell-pepper": "Peperone|peperoni",
  onion: "Cipolla",
  cucumber: "Cetriolo",
  eggplant: "Melanzana|melanzane",
  mushrooms: "Funghi|champignon",
  "green-beans": "Fagiolini",
  cauliflower: "Cavolfiore",
  avocado: "Avocado",
  "sweet-corn": "Mais dolce|mais",
  "sweet-potato": "Patata dolce|patata americana",
  "tomato-sauce": "Passata di pomodoro|salsa di pomodoro|sugo",
  apple: "Mela",
  banana: "Banana",
  orange: "Arancia",
  mandarin: "Mandarino|clementina",
  pear: "Pera",
  peach: "Pesca",
  apricot: "Albicocca",
  kiwi: "Kiwi",
  strawberries: "Fragole",
  blueberries: "Mirtilli",
  cherries: "Ciliegie",
  grapes: "Uva",
  watermelon: "Anguria|cocomero",
  melon: "Melone",
  pineapple: "Ananas",
  "dates-dried": "Datteri secchi|datteri",
  raisins: "Uvetta|uva passa",
  almonds: "Mandorle|frutta secca",
  walnuts: "Noci|frutta secca",
  hazelnuts: "Nocciole|frutta secca",
  peanuts: "Arachidi|noccioline|frutta secca",
  pistachios: "Pistacchi|frutta secca",
  cashews: "Anacardi|frutta secca",
  "peanut-butter": "Burro di arachidi",
  "chia-seeds": "Semi di chia|semi",
  "olive-oil": "Olio d'oliva|olio extravergine|olio",
  mayonnaise: "Maionese",
  ketchup: "Ketchup",
  pesto: "Pesto",
  honey: "Miele",
  sugar: "Zucchero",
  jam: "Marmellata|confettura",
  "dark-chocolate": "Cioccolato fondente|cioccolato",
  "milk-chocolate": "Cioccolato al latte|cioccolato",
  "ice-cream": "Gelato",
  "potato-chips": "Patatine in busta|patatine|chips",
  "orange-juice": "Succo d'arancia|spremuta|succo",
  cola: "Cola|bibita gassata",
  coffee: "Caffè, senza zucchero|caffè|espresso",
  beer: "Birra",
  wine: "Vino|vino rosso|vino bianco",
};
