import type { FoodNames } from "../catalog";

export const pl: FoodNames = {
  "pasta-dry": "Makaron, suchy|spaghetti|penne",
  "pasta-cooked": "Makaron, gotowany|spaghetti|penne",
  "wholewheat-pasta-dry": "Makaron pełnoziarnisty, suchy",
  "rice-dry": "Ryż, suchy|ryż biały",
  "rice-cooked": "Ryż, gotowany|ryż biały",
  "brown-rice-cooked": "Ryż brązowy, gotowany|ryż pełnoziarnisty",
  "bread-white": "Chleb pszenny|chleb|pieczywo|tost",
  "bread-wholemeal": "Chleb pełnoziarnisty|chleb razowy|chleb",
  rusks: "Sucharki",
  crackers: "Krakersy",
  oats: "Płatki owsiane|owsianka",
  cornflakes: "Płatki kukurydziane|płatki",
  muesli: "Musli|płatki|granola",
  "couscous-cooked": "Kuskus, ugotowany",
  "quinoa-cooked": "Komosa ryżowa, ugotowana|quinoa",
  "polenta-cooked": "Polenta, ugotowana|kasza kukurydziana",
  "potatoes-boiled": "Ziemniaki gotowane|ziemniaki",
  "french-fries": "Frytki",
  "pizza-margherita": "Pizza margherita|pizza",
  croissant: "Rogalik francuski|croissant",
  "butter-cookies": "Herbatniki maślane|ciastka|herbatniki",
  "chicken-breast-raw": "Pierś z kurczaka, surowa|kurczak",
  "chicken-breast-cooked": "Pierś z kurczaka, pieczona|kurczak|kurczak grillowany",
  "turkey-breast-raw": "Pierś z indyka, surowa|indyk",
  "beef-lean-raw": "Chuda wołowina, surowa|stek|wołowina",
  "beef-ground-raw": "Mielona wołowina, surowa|mięso mielone|burger",
  "pork-loin-raw": "Schab wieprzowy, surowy|schab|wieprzowina",
  "pork-sausage-raw": "Kiełbasa wieprzowa, surowa|kiełbasa",
  "cooked-ham": "Szynka gotowana|szynka",
  "cured-ham": "Szynka dojrzewająca|szynka parmeńska|szynka",
  bresaola: "Bresaola|suszona wołowina",
  salami: "Salami",
  egg: "Jajko|jajka|jaja",
  "egg-white": "Białko jaja|jajka",
  "tuna-in-water": "Tuńczyk w sosie własnym, odsączony|tuńczyk z puszki|tuńczyk",
  "tuna-in-oil": "Tuńczyk w oleju, odsączony|tuńczyk z puszki|tuńczyk",
  "salmon-raw": "Łosoś, surowy|łosoś",
  "cod-raw": "Dorsz, surowy|ryba",
  "shrimp-raw": "Krewetki, surowe|krewetki",
  tofu: "Tofu",
  "whey-protein": "Białko serwatkowe w proszku|odżywka białkowa|shake",
  "yogurt-plain": "Jogurt naturalny|jogurt",
  "greek-yogurt-0": "Jogurt grecki 0%|skyr",
  "greek-yogurt-full": "Jogurt grecki pełnotłusty|jogurt grecki",
  mozzarella: "Mozzarella, świeża|mozzarella|ser",
  parmesan: "Parmezan|ser tarty|ser",
  ricotta: "Ricotta|twaróg|ser",
  cheddar: "Cheddar|ser żółty|ser",
  feta: "Feta|ser",
  "cottage-cheese": "Serek wiejski|ser",
  butter: "Masło",
  "milk-whole": "Mleko pełne 3,2%|mleko",
  "milk-semi": "Mleko 1,5%|mleko półtłuste|mleko",
  "milk-skim": "Mleko odtłuszczone|mleko",
  "chickpeas-cooked": "Ciecierzyca, gotowana|ciecierzyca z puszki",
  "chickpeas-dry": "Ciecierzyca, sucha",
  "lentils-cooked": "Soczewica, gotowana",
  "lentils-dry": "Soczewica, sucha",
  "beans-cooked": "Fasola, gotowana|fasola czerwona",
  peas: "Groszek zielony|groszek",
  hummus: "Hummus",
  tomato: "Pomidor|pomidory",
  lettuce: "Sałata",
  carrot: "Marchew|marchewka",
  zucchini: "Cukinia",
  broccoli: "Brokuł|brokuły",
  spinach: "Szpinak",
  "bell-pepper": "Papryka",
  onion: "Cebula",
  cucumber: "Ogórek",
  eggplant: "Bakłażan|oberżyna",
  mushrooms: "Pieczarki|grzyby",
  "green-beans": "Fasolka szparagowa",
  cauliflower: "Kalafior",
  avocado: "Awokado",
  "sweet-corn": "Kukurydza słodka|kukurydza",
  "sweet-potato": "Batat|słodki ziemniak",
  "tomato-sauce": "Passata pomidorowa|sos pomidorowy",
  apple: "Jabłko",
  banana: "Banan",
  orange: "Pomarańcza",
  mandarin: "Mandarynka|klementynka",
  pear: "Gruszka",
  peach: "Brzoskwinia",
  apricot: "Morela",
  kiwi: "Kiwi",
  strawberries: "Truskawki",
  blueberries: "Borówki|jagody",
  cherries: "Czereśnie|wiśnie",
  grapes: "Winogrona",
  watermelon: "Arbuz",
  melon: "Melon",
  pineapple: "Ananas",
  "dates-dried": "Daktyle suszone|daktyle",
  raisins: "Rodzynki",
  almonds: "Migdały|orzechy",
  walnuts: "Orzechy włoskie|orzechy",
  hazelnuts: "Orzechy laskowe|orzechy",
  peanuts: "Orzeszki ziemne|orzechy",
  pistachios: "Pistacje|orzechy",
  cashews: "Orzechy nerkowca|nerkowce|orzechy",
  "peanut-butter": "Masło orzechowe",
  "chia-seeds": "Nasiona chia|chia",
  "olive-oil": "Oliwa z oliwek|oliwa|olej",
  mayonnaise: "Majonez",
  ketchup: "Ketchup",
  pesto: "Pesto",
  honey: "Miód",
  sugar: "Cukier",
  jam: "Dżem|konfitura",
  "dark-chocolate": "Czekolada gorzka|czekolada",
  "milk-chocolate": "Czekolada mleczna|czekolada",
  "ice-cream": "Lody",
  "potato-chips": "Chipsy ziemniaczane|chipsy",
  "orange-juice": "Sok pomarańczowy|sok",
  cola: "Cola|napój gazowany",
  coffee: "Kawa czarna|kawa|espresso",
  beer: "Piwo",
  wine: "Wino|wino czerwone|wino białe",
};
