import type { FoodNames } from "../catalog";

export const pt: FoodNames = {
  "pasta-dry": "Macarrão, cru|espaguete|massa",
  "pasta-cooked": "Macarrão, cozido|espaguete|massa",
  "wholewheat-pasta-dry": "Macarrão integral, cru|massa integral",
  "rice-dry": "Arroz, cru|arroz branco",
  "rice-cooked": "Arroz, cozido|arroz branco",
  "brown-rice-cooked": "Arroz integral, cozido",
  "bread-white": "Pão branco|pão|pão de forma|pão francês",
  "bread-wholemeal": "Pão integral|pão",
  rusks: "Torradas",
  crackers: "Biscoito de água e sal|cracker",
  oats: "Aveia em flocos|aveia|mingau",
  cornflakes: "Flocos de milho|cereal|sucrilhos",
  muesli: "Muesli|cereal|granola",
  "couscous-cooked": "Cuscuz marroquino, cozido|cuscuz",
  "quinoa-cooked": "Quinoa, cozida",
  "polenta-cooked": "Polenta, cozida|angu",
  "potatoes-boiled": "Batata cozida|batata",
  "french-fries": "Batata frita|fritas",
  "pizza-margherita": "Pizza marguerita|pizza",
  croissant: "Croissant",
  "butter-cookies": "Biscoito amanteigado|biscoito|bolacha",
  "chicken-breast-raw": "Peito de frango, cru|frango",
  "chicken-breast-cooked": "Peito de frango, cozido|frango|frango grelhado",
  "turkey-breast-raw": "Peito de peru, cru|peru",
  "beef-lean-raw": "Carne bovina magra, crua|bife|patinho|carne",
  "beef-ground-raw": "Carne moída, crua|hambúrguer",
  "pork-loin-raw": "Lombo de porco, cru|bisteca|porco",
  "pork-sausage-raw": "Linguiça de porco, crua|linguiça|salsicha",
  "cooked-ham": "Presunto cozido|presunto",
  "cured-ham": "Presunto cru|presunto de Parma",
  bresaola: "Bresaola|carne curada",
  salami: "Salame",
  egg: "Ovo|ovos",
  "egg-white": "Clara de ovo|ovos",
  "tuna-in-water": "Atum em água, escorrido|atum em lata|atum",
  "tuna-in-oil": "Atum em óleo, escorrido|atum em lata|atum",
  "salmon-raw": "Salmão, cru|salmão",
  "cod-raw": "Bacalhau fresco, cru|peixe",
  "shrimp-raw": "Camarão, cru|camarão",
  tofu: "Tofu firme|tofu",
  "whey-protein": "Whey protein em pó|proteína em pó|shake",
  "yogurt-plain": "Iogurte natural|iogurte",
  "greek-yogurt-0": "Iogurte grego 0%|iogurte grego desnatado|skyr",
  "greek-yogurt-full": "Iogurte grego integral|iogurte grego",
  mozzarella: "Muçarela fresca|mussarela|queijo",
  parmesan: "Parmesão|queijo ralado|queijo",
  ricotta: "Ricota|queijo",
  cheddar: "Cheddar|queijo",
  feta: "Feta|queijo",
  "cottage-cheese": "Queijo cottage|queijo",
  butter: "Manteiga",
  "milk-whole": "Leite integral|leite",
  "milk-semi": "Leite semidesnatado|leite",
  "milk-skim": "Leite desnatado|leite",
  "chickpeas-cooked": "Grão-de-bico, cozido",
  "chickpeas-dry": "Grão-de-bico, seco",
  "lentils-cooked": "Lentilha, cozida",
  "lentils-dry": "Lentilha, seca",
  "beans-cooked": "Feijão, cozido|feijão",
  peas: "Ervilha|ervilhas",
  hummus: "Homus|hummus",
  tomato: "Tomate",
  lettuce: "Alface|salada",
  carrot: "Cenoura",
  zucchini: "Abobrinha",
  broccoli: "Brócolis",
  spinach: "Espinafre",
  "bell-pepper": "Pimentão",
  onion: "Cebola",
  cucumber: "Pepino",
  eggplant: "Berinjela",
  mushrooms: "Cogumelos|champignon",
  "green-beans": "Vagem",
  cauliflower: "Couve-flor",
  avocado: "Abacate",
  "sweet-corn": "Milho verde|milho",
  "sweet-potato": "Batata-doce",
  "tomato-sauce": "Passata de tomate|molho de tomate",
  apple: "Maçã",
  banana: "Banana",
  orange: "Laranja",
  mandarin: "Tangerina|mexerica|bergamota",
  pear: "Pera",
  peach: "Pêssego",
  apricot: "Damasco",
  kiwi: "Kiwi",
  strawberries: "Morangos|morango",
  blueberries: "Mirtilos|blueberry",
  cherries: "Cerejas",
  grapes: "Uvas|uva",
  watermelon: "Melancia",
  melon: "Melão",
  pineapple: "Abacaxi",
  "dates-dried": "Tâmaras secas|tâmaras",
  raisins: "Uvas-passas|passas",
  almonds: "Amêndoas|castanhas",
  walnuts: "Nozes|castanhas",
  hazelnuts: "Avelãs|castanhas",
  peanuts: "Amendoim",
  pistachios: "Pistache",
  cashews: "Castanha de caju|castanhas",
  "peanut-butter": "Pasta de amendoim",
  "chia-seeds": "Sementes de chia|chia",
  "olive-oil": "Azeite de oliva|azeite|óleo",
  mayonnaise: "Maionese",
  ketchup: "Ketchup",
  pesto: "Pesto",
  honey: "Mel",
  sugar: "Açúcar",
  jam: "Geleia",
  "dark-chocolate": "Chocolate amargo|chocolate meio amargo|chocolate",
  "milk-chocolate": "Chocolate ao leite|chocolate",
  "ice-cream": "Sorvete|gelato",
  "potato-chips": "Batata chips|salgadinho",
  "orange-juice": "Suco de laranja|suco",
  cola: "Refrigerante de cola|refrigerante|cola",
  coffee: "Café sem açúcar|café|espresso",
  beer: "Cerveja",
  wine: "Vinho|vinho tinto|vinho branco",
};
