import type { QuoteTexts } from "./types";

export const de: QuoteTexts = {
  // discipline · soft
  ds01: "Auch kleine Schritte bringen dich voran.",
  ds02: "Du musst nicht auf den richtigen Moment warten. Fang sanft an.",
  ds03: "Heute ein bisschen tun schlägt viel planen.",
  ds04: "Beständigkeit ist ein Geschenk an die Person, die du morgen bist.",
  ds05: "Eine fokussierte Stunde kann die Form eines Tages verändern.",
  ds06: "Halte das Versprechen von heute Morgen, auch wenn es klein ist.",
  ds07: "Disziplin kann leise sein. Sie taucht einfach wieder auf.",
  ds08: "Fang mit dem leichtesten Schritt an. Der Schwung macht den Rest.",
  ds09: "Man kann langsam gehen und trotzdem weit kommen.",
  ds10: "Bring eine Sache zu Ende, bevor du die nächste anfängst.",
  ds11: "Ein klarer Plan macht schwere Dinge leichter.",
  ds12: "Heute zählt, auch wenn es nicht perfekt ist.",
  ds13: "Schütz deine Aufmerksamkeit: Dort lebt dein Tag.",
  ds14: "Erschaffe etwas.",
  ds15: "Fang einfach an. Den Rest findest du unterwegs heraus.",
  ds16: "Hetz dich nicht beim Aufstieg.",
  ds17: "Vielleicht passiert es nicht über Nacht, aber wenn du aufgibst, passiert es nie.",
  ds18: "Es geht nur darum, klar zu wissen, was du willst.",
  ds19: "Erfüll dir deine Träume. Alles Liebe, GetControl.",
  ds20: "Wir fangen gerade erst an.",
  ds21: "Du bist da, um zu erschaffen.",
  ds22: "Wenn die Vorfreude ein bisschen größer ist als die Angst, fängst du an.",
  ds23: "Die Möglichkeiten sind endlos.",
  // discipline · direct
  dd01: "Motivation kommt und geht. Mach es trotzdem.",
  dd02: "Entscheide einmal und hör auf, es wieder aufzurollen.",
  dd03: "Leg das Handy weg und fang an.",
  dd04: "Ein Plan funktioniert nur, wenn du dich bewegst.",
  dd05: "Zehn Minuten jetzt schlagen eine Stunde „irgendwann“.",
  dd06: "Erledigt ist besser als perfekt. Schließ es ab.",
  dd07: "Dein Kalender zeigt deine Prioritäten. Schau nach.",
  dd08: "Hör auf, auf die richtige Stimmung zu warten. Fang mit der Arbeit an.",
  dd09: "Mach das Schwere zuerst, solange du frisch bist.",
  dd10: "Wenn es zwei Minuten dauert, mach es jetzt.",
  dd11: "Sag heute zu etwas Nein, damit du zu dem Ja sagen kannst, was zählt.",
  dd12: "Ausreden sind leicht. Ergebnisse brauchen Wiederholungen.",
  dd13: "Wähl eine Priorität und verteidige sie.",
  dd14: "Das muss passieren.",
  dd15: "Plan B ist nur Plan A mit mehr Zeit.",
  dd16: "Träumen und Handeln sind zwei verschiedene Dinge.",
  dd17: "Warte nicht auf Glück. Mach dein eigenes.",
  dd18: "Wenn du es so sehr willst, finde einen Weg. Ich vertraue dir.",
  dd19: "Der Cheatcode heißt Disziplin und Beständigkeit.",
  dd20: "Bring zu Ende, was du angefangen hast.",
  dd21: "Sorg dafür, dass deine Zeit viel wert ist.",
  dd22: "Zeit wird nicht erstattet. Nutze sie mit Absicht.",
  dd23: "Handle, als hättest du es schon.",
  dd24: "Wenn nicht jetzt, wann dann?",
  dd25: "Der nächste Wurf zählt mehr als der letzte Fehler.",
  dd26: "Wenn jemand anders es hat, warum nicht du?",
  dd27: "Glaub maßlos an deine Ziele.",
  dd28: "Steh deinem eigenen Ziel nicht im Weg.",
  dd29: "Alles, was du willst, liegt auf der anderen Seite der Angst.",
  dd30: "Du bist bereit geboren.",
  // discipline · hard
  dh01: "Niemand kommt und macht es für dich.",
  dh02: "Du hast gesagt, du machst es. Also mach es.",
  dh03: "Bequemlichkeit heute, Reue morgen. Entscheide.",
  dh04: "Keine Ausreden. Nicht heute.",
  dh05: "Die Uhr wartet nicht auf deine Laune. An die Arbeit.",
  dh06: "Wollen reicht nicht. Verdien es dir.",
  dh07: "Hör auf zu scrollen. Fang an zu machen.",
  dh08: "Jeder Aufschub ist eine Entscheidung. Triff eine bessere.",
  dh09: "Arbeit schlägt Gerede. Jedes einzelne Mal.",
  dh10: "Du weißt genau, was zu tun ist. Los.",
  dh11: "Disziplin jetzt oder Enttäuschung später.",
  dh12: "„Morgen“ ist der Ort, an dem Pläne sterben. Handle heute.",
  dh13: "Die Arbeit erledigt sich nicht von selbst. Die Veränderung auch nicht.",
  dh14: "Alles rein.",
  dh15: "Große Träume verlangen große Opfer.",
  dh16: "Erhöh das Opfer oder senk den Wunsch.",
  dh17: "Spiel, um zu gewinnen.",
  dh18: "Kassier so viele Niederlagen, dass dich Siege nicht mehr überraschen.",
  dh19: "Manifestieren bringt nichts. Handle.",
  dh20: "Schlimmstenfalls schaffst du es. Bestenfalls schaffst du es größer.",
  dh21: "Du bist nicht für Mittelmaß gemacht.",
  dh22: "Um zu bekommen, was du nie hattest, tu, was du nie getan hast.",
  dh23: "Nicht mal der Himmel ist deine Grenze. Ziel höher.",
  dh24: "Je höher am Berg, desto tückischer der Weg.",
  dh25: "Gewinn in der aussichtslosen Lage.",
  dh26: "Die Wahrheit ist: Niemand kommt, um dich zu retten.",
  dh27: "Wenn niemand über deine Ziele lacht, sind sie zu klein.",
  dh28: "Die Welt macht Wellen. Surf oder geh unter: Du entscheidest.",
  dh29: "Ohne Risiko kein Gewinn.",
  // habits · soft
  hs01: "Eine Gewohnheit ist eine Entscheidung, die du freundlich wiederholst.",
  hs02: "Mach es so klein, dass du nicht Nein sagen kannst.",
  hs03: "Gleiche Zeit, gleicher Ort: Lass dich von der Routine tragen.",
  hs04: "Einmal auslassen ist menschlich. Zurückkommen ist die Gewohnheit.",
  hs05: "Feier die kleinen Siege: Sie bauen die großen.",
  hs06: "Deine Umgebung kann die halbe Arbeit machen. Richte sie ein.",
  hs07: "Verknüpf eine neue Gewohnheit mit etwas, das du schon tust.",
  hs08: "Fortschritt, den du wiederholen kannst, schlägt Fortschritt, den du nicht wiederholen kannst.",
  hs09: "Bereite heute Abend eine Sache für morgen früh vor.",
  hs10: "Gewohnheiten wachsen leise, wie Pflanzen. Gieß weiter.",
  hs11: "Eine gute Gewohnheit macht die nächste leichter.",
  hs12: "Achte darauf, was du im Autopilot tust. Wähl eine Sache, die du verbesserst.",
  hs13: "Fang an, wo du bist, mit dem, was du hast.",
  hs14: "Morgenspaziergang?",
  hs15: "Nimm dir Zeit zum Nachdenken.",
  hs16: "Such Wissen.",
  hs17: "Verbring mehr Zeit damit, dich kennenzulernen, und weniger damit, alle um dich herum aufzusaugen.",
  hs18: "Es zu versuchen ist schon Veränderung.",
  // habits · direct
  hd01: "Deine Tage bestehen aus Gewohnheiten. Bau bessere Tage.",
  hd02: "Lass nie zweimal hintereinander aus.",
  hd03: "Schreib es auf, sonst erzählst du dir am Ende Geschichten.",
  hd04: "Mach die richtige Wahl zur einfachen.",
  hd05: "Entferne einen Auslöser der Gewohnheit, die du loswerden willst.",
  hd06: "Wiederholung schlägt Intensität.",
  hd07: "Wenn es nicht im Kalender steht, ist es nur ein Wunsch.",
  hd08: "Kleine Taten jeden Tag, große Ergebnisse in einem Jahr.",
  hd09: "Mieser Tag? Mach die Minimalversion. Zählt trotzdem.",
  hd10: "Auch dein Handy ist eine Gewohnheit. Entscheide, wer das Sagen hat.",
  hd11: "Erst auftauchen. Dann besser werden.",
  hd12: "Sammle kleine Siege vor Mittag.",
  hd13: "Du wirst, was du wiederholst.",
  hd14: "Fokus, für dich.",
  hd15: "Entwickle dich oder wiederhole dich.",
  hd16: "Durchbrich das Muster.",
  hd17: "Schwung korrigiert Fehler schneller als Reue.",
  hd18: "Handle nicht aus dem Impuls heraus.",
  hd19: "Der schnellste Weg, eine Idee zu töten: zehn Leute fragen, was sie davon halten.",
  hd20: "Das Leben ist nicht zum Stillstehen gemacht. Beweg dich, immer.",
  hd21: "Wer sein eigenes Holz hackt, dem wird zweimal warm.",
  hd22: "Ugh, ich hasse langweilige Dinge. Du nicht?",
  // habits · hard
  hh01: "Deine Gewohnheiten stimmen über deine Zukunft ab. Prüf die Auszählung.",
  hh02: "Jedes „nur dieses eine Mal“ ist eine verkleidete Gewohnheit.",
  hh03: "Dir fehlt nicht die Zeit. Dir fehlt eine Routine.",
  hh04: "Brich die Serie der Ausreden, nicht die der Arbeit.",
  hh05: "Gleiche Gewohnheiten, gleiche Ergebnisse. Ändere etwas.",
  hh06: "Hör auf, die Schlummertaste zu drücken. Gewinn die erste Minute.",
  hh07: "Zwei ausgelassene Tage sind der Anfang vom Aufgeben. Komm heute zurück.",
  hh08: "Die Gewohnheit, der du ausweichst, ist die, die du brauchst.",
  hh09: "Hör auf, von vorn anzufangen. Mach weiter.",
  hh10: "Wenn du es weiter tust, entscheidest du dich dafür.",
  hh11: "Routine ist nicht langweilig. Chaos ist teuer.",
  hh12: "Lösch die Ablenkung. Heute, nicht morgen.",
  hh13: "Gute Vorsätze ohne Gewohnheiten sind nur Lärm.",
  hh14: "Du kennst deinen nächsten Schritt. Du hoffst nur auf einen leichteren.",
  // character · soft
  cs01: "Freundlichkeit und Stärke passen zusammen.",
  cs02: "Halte kleine Versprechen an dich selbst. Daraus wird Vertrauen.",
  cs03: "Du kannst geduldig mit dir sein und trotzdem hoch zielen.",
  cs04: "Ehrlichkeit beginnt bei dem, was du dir selbst erzählst.",
  cs05: "Tu das Richtige, auch wenn niemand hinschaut.",
  cs06: "Mut ist oft ein leises „Ich versuch's nochmal“.",
  cs07: "Deine Werte sind ein Kompass. Schau heute drauf.",
  cs08: "Hör heute mehr zu, als du redest.",
  cs09: "Dankbarkeit macht das Gewöhnliche zu genug.",
  cs10: "Um Hilfe bitten ist okay. Auch das ist Stärke.",
  cs11: "Wie du andere behandelst, formt, wer du wirst.",
  cs12: "Die Mühe verdient Stolz, nicht nur das Ergebnis.",
  cs13: "Wachs in deinem Tempo. Vergleichen ist keine Landkarte.",
  cs14: "Was ist eigentlich deine Philosophie?",
  cs15: "Wie Geld sind auch Gefühle eine Investition.",
  cs16: "Innen bist du mehr.",
  cs17: "An dich zu glauben kostet nichts. Selbstvertrauen ist gratis.",
  cs18: "Der Bauplan heißt: an dich glauben.",
  cs19: "Sei ein Geheimnis.",
  cs20: "Das Leben ist ein Spiegel des Geistes.",
  cs21: "Kleide dich schlicht, für dich, nicht um zu beeindrucken.",
  cs22: "Hab den Mut, in etwas Neuem schlecht zu sein.",
  cs23: "Was hat die Liebe an sich, dass wir den Kopf verlieren?",
  // character · direct
  cd01: "Charakter ist, was du tust, wenn es unbequem ist.",
  cd02: "Steh zu deinen Fehlern. Dann behebe sie.",
  cd03: "Sag, was du meinst. Tu, was du sagst.",
  cd04: "Respekt verdient man sich in kleinen Momenten.",
  cd05: "Sei pünktlich: Das zeigt anderen, dass sie zählen.",
  cd06: "Wenn richtig und bequem auseinandergehen, wähl richtig.",
  cd07: "Jammern ändert nichts. Handeln schon.",
  cd08: "Dein Wort ist ein Vertrag. Halte es.",
  cd09: "Werde die Person, die deine Pläne brauchen.",
  cd10: "Gib zu, was du nicht weißt. Dann lern es.",
  cd11: "Ruhe ist eine Fähigkeit. Übe sie heute.",
  cd12: "Klarheit ohne Härte, Festigkeit ohne Kälte.",
  cd13: "Integrität heißt, es richtig zu machen, wenn Abkürzungen leicht sind.",
  cd14: "Erzähl niemandem von deinen Träumen.",
  cd15: "Du gehörst dir, und nur dir.",
  cd16: "Trau Taten mehr als Worten.",
  cd17: "Wütend sein ist okay. Grausam sein nie.",
  cd18: "Entscheidungen aus Wut lassen sich nicht rückgängig machen.",
  cd19: "Das erste Opfer deiner Wut bist du.",
  cd20: "Fehler gemacht? Entschuldige dich.",
  cd21: "Vermisst du jemanden? Melde dich.",
  cd22: "Verliebt? Sag es.",
  cd23: "Mach dich nicht rar: Du lebst nur einmal.",
  cd24: "Widersprich, wenn nötig. Es ist deine Meinung.",
  cd25: "Kümmere dich um deinen Charakter, nicht um deinen Ruf: Das eine bist du, das andere denken die Leute.",
  cd26: "Vertrau deinem Instinkt.",
  cd27: "Manchmal musst du deinem eigenen Denken mehr trauen als allen um dich herum.",
  cd28: "Glaub an Abneigung auf den ersten Blick, wie du an Liebe auf den ersten Blick glaubst.",
  cd29: "Nicht alle werden deine Vision sehen. Bleib dran.",
  cd30: "Du musstest nie daran glauben, um es versuchen zu dürfen.",
  cd31: "Handeln heilt Angst.",
  // character · hard
  ch01: "Hör auf, Schuld zu verteilen. Übernimm Verantwortung.",
  ch02: "Reden ist billig. Zeig es.",
  ch03: "Wenn es dir wichtig ist, beweis es heute.",
  ch04: "Niemand schuldet dir eine Abkürzung.",
  ch05: "Ehrliche Frage: Hast du viel zu tun, oder weichst du etwas aus?",
  ch06: "Ausreden ändern keine Ergebnisse.",
  ch07: "Halte dein Wort, vor allem dir selbst gegenüber.",
  ch08: "Die Angst hat eine Stimme, aber kein Veto.",
  ch09: "Warte nicht auf Mut. Handle, und er kommt.",
  ch10: "Leg die Latte höher. Und bleib dort.",
  ch11: "Verantwortung ist keine Last. Sie ist Macht.",
  ch12: "Hör auf zu fragen, ob es fair ist. Frag, was als Nächstes kommt.",
  ch13: "Druck zeigt, wer du bist. Bereite dich jetzt vor.",
  ch14: "Sollen sie doch denken, was zum Teufel sie wollen.",
  ch15: "Kritik? Nicht dein Problem.",
  ch16: "Mach dich ruhig lächerlich. Sei du.",
  ch17: "Poste es, und hab keine Angst davor, was andere denken.",
  ch18: "Fakt ist: Du brauchst nichts von niemandem.",
  ch19: "Wenn sie dich nicht wiedererkennen, machst du Fortschritte.",
  ch20: "Sie haben keine Ahnung, wer du werden wirst.",
  ch21: "Du bist deine größte Angst und deine schönste Fantasie.",
  ch22: "Du kannst überall auf der Welt hinreisen, aber dir selbst entkommst du nicht.",
  ch23: "In einem Raum voller Spiegel wärst du von Gewinnern umgeben.",
  ch24: "Triff Entscheidungen und schau nicht zurück.",
  ch25: "Sorg nur dafür, dass du dich über diesen ganzen Wahnsinn erhebst.",
  ch26: "Vögel, die im Käfig geboren sind, halten Fliegen für eine Krankheit.",
  ch27: "Kluge Leute wissen, was sie sind.",
  ch28: "Wähl deinen Skandal und deinen Erfolg.",
  ch29: "Nichts für ungut, aber wow.",
  ch30: "Ätsch bätsch.",
  ch31: "Gesunder Menschenverstand? Ach, der ist so… gewöhnlich.",
  // recovery · soft
  rs01: "Ruhe gehört zur Arbeit, sie ist keine Pause davon.",
  rs02: "Auch an einem langsamen Tag bist du da. Das reicht.",
  rs03: "Atme aus. Du musst heute nicht alles schaffen.",
  rs04: "Rückschläge gehören zum Weg, sie sind nicht sein Ende.",
  rs05: "Schlaf heute Nacht gut. Morgen wird es dir danken.",
  rs06: "Sei so freundlich zu dir, wie du es zu jemandem wärst, den du liebst.",
  rs07: "Pausieren ist okay. Denk nur daran zurückzukommen.",
  rs08: "Heute ist das Ziel, dich zu erholen. Das ist erlaubt.",
  rs09: "Geh ein paar Schritte, schau in den Himmel, fang neu an.",
  rs10: "Du hast schon schwere Tage geschafft. Diesen schaffst du auch.",
  rs11: "Lass gestern los. Heute ist eine neue Seite.",
  rs12: "Ein Neustart ist kein Scheitern. Er ist Wartung.",
  rs13: "Ruhige Minuten sind der Weg, wie Energie zurückkommt.",
  rs14: "Nimm dir Zeit zu heilen.",
  rs15: "Freude hat die Gewohnheit zurückzukommen.",
  rs16: "Später wird es Sinn ergeben.",
  rs17: "Lass es geschehen.",
  rs18: "Lass das Licht herein.",
  rs19: "Irgendwann, irgendwie.",
  rs20: "Selbst was zerbrochen ist, lässt Licht durch.",
  rs21: "Ein Schritt zurück gehört auch zum Tanz.",
  rs22: "Etwas zu verlieren ist nicht immer ein Verlust.",
  rs23: "Mal gut, mal schlecht. Dinge kommen, Dinge gehen.",
  rs24: "Vergiss nicht, dass auch du Teil der Natur bist.",
  rs25: "Auch Menschen können Museen sein, voller Geschichte, die sie nicht mehr berühren können.",
  rs26: "Du kannst alles sein, alles tun, neu anfangen.",
  rs27: "Es ist okay, hinter dir zu lassen, was sich nicht richtig anfühlt, auch wenn es alles ist, was du kennst.",
  rs28: "Tu es für dich und für all die Nächte, in denen du nur dich hattest.",
  rs29: "Wenn du Frieden willst, such ihn bei dir oder bei jemandem, der denkt wie du.",
  rs30: "Juhu, hurra, tschüss, danke!",
  rs31: "Keine Ahnung, Zeit für das Et cetera.",
  rs32: "Gute Nacht, und trink genug Wasser.",
  // recovery · direct
  rd01: "Ausgerutscht. Okay. Nächster Schritt.",
  rd02: "Ruh dich absichtlich aus, nicht erst beim Zusammenbruch.",
  rd03: "Einen Tag verloren? Verlier nicht die Woche.",
  rd04: "Erst erholen, dann zurückkommen. In dieser Reihenfolge.",
  rd05: "Schlechte Momente machen kein schlechtes Leben.",
  rd06: "Behalte die Lektion, lass die Schuld los.",
  rd07: "Mach den Bildschirm heute eine Stunde früher aus.",
  rd08: "Eine Pause ist ein Werkzeug. Nutz sie und komm zurück.",
  rd09: "Plan verpasst? Mach einen kleineren und halte ihn.",
  rd10: "Alles steckt fest? Ändere eine Sache und schau neu hin.",
  rd11: "Müdigkeit ist eine Information, keine Ausrede.",
  rd12: "Starte heute neu. Nicht am Montag.",
  rd13: "Zu viel zu tun? Schreib den nächsten winzigen Schritt auf.",
  rd14: "Manchmal ist der einzige Fortschritt, nicht aufzugeben.",
  rd15: "Je weniger du dir Sorgen machst, desto mehr lebst du.",
  rd16: "Gut zu leben ist die beste Rache.",
  rd17: "Lerne, das Leben zu genießen, ohne Publikum zu brauchen.",
  rd18: "Alles Verlorene lässt sich wiederfinden, außer verschwendeter Zeit.",
  rd19: "Eine positive Einstellung macht einen Unterschied, nicht den Unterschied.",
  rd20: "Freiheit beginnt, wenn du merkst, dass der Käfig aus Gedanken besteht.",
  rd21: "Verschwinde eine Weile und komm mit mehr Schwung zurück.",
  rd22: "Schau nicht zurück. Da gehst du nicht hin.",
  rd23: "Die Vergangenheit liegt nicht mehr in deiner Hand. Die Zukunft schon.",
  rd24: "Sei ein bisschen egoistisch mit deiner Zeit.",
  // recovery · hard
  rh01: "Hinfallen, aufstehen. Keine Reden.",
  rh02: "Selbstmitleid verschwendet die Zeit, die du zum Erholen brauchst.",
  rh03: "Gestern ist vorbei. Hör auf, es abzuspielen.",
  rh04: "Ein schlechter Tag ist ein Ereignis. Zwei sind eine Entscheidung.",
  rh05: "Ausruhen ja. Verstecken nein.",
  rh06: "Du hast schon öfter neu angefangen. Mach es wieder, jetzt.",
  rh07: "Rückschlag? Gut. Jetzt weißt du, was du reparieren musst.",
  rh08: "Warte nicht auf den perfekten Neustart. Nimm den unperfekten.",
  rh09: "Zurück ins Spiel. Die Bank ist nicht dein Platz.",
  rh10: "Erhol dich richtig, dann komm mit vollem Tempo zurück.",
  rh11: "Fehler bezahlt man mit Taten, nicht mit Schuldgefühlen.",
  rh12: "Das Comeback beginnt mit dem nächsten kleinen Schritt.",
  rh13: "Kein Drama. Reset und los.",
  rh14: "Womp womp. Nächster.",
};
