import type { QuoteTexts } from "./types";

export const en: QuoteTexts = {
  // discipline · soft
  ds01: "Small steps still move you forward.",
  ds02: "You don't have to wait for the right moment. Begin gently.",
  ds03: "Doing a little today beats planning a lot.",
  ds04: "Consistency is a gift to the person you'll be tomorrow.",
  ds05: "One focused hour can change the shape of a day.",
  ds06: "Keep this morning's promise, even if it's a small one.",
  ds07: "Discipline can be quiet. It simply shows up again.",
  ds08: "Start with the easiest step. Momentum will do the rest.",
  ds09: "You can go slowly and still go far.",
  ds10: "Finish one thing before starting the next.",
  ds11: "A clear plan makes hard things lighter.",
  ds12: "Today counts, even if it isn't perfect.",
  ds13: "Protect your attention: it's where your day lives.",
  ds14: "Create something.",
  ds15: "Just start. You'll figure it out along the way.",
  ds16: "Don't rush the climb.",
  ds17: "Maybe it won't happen overnight, but if you quit it won't happen at all.",
  ds18: "It's just being intentional about what you want.",
  ds19: "Fulfill your dreams. Love, GetControl.",
  ds20: "We're just getting started.",
  ds21: "You were created to create.",
  ds22: "When you're a little more excited than afraid, that's when you begin.",
  ds23: "The possibilities are endless.",
  // discipline · direct
  dd01: "Motivation comes and goes. Do it anyway.",
  dd02: "Decide once, then stop reopening the question.",
  dd03: "Put the phone down and start.",
  dd04: "A plan only works when you move.",
  dd05: "Ten minutes now beat an hour \"someday\".",
  dd06: "Done is better than perfect. Close it.",
  dd07: "Your calendar shows your priorities. Check it.",
  dd08: "Stop waiting for the right mood. Start the work.",
  dd09: "Do the hard thing first, while you're fresh.",
  dd10: "If it takes two minutes, do it now.",
  dd11: "Say no to something today, so you can say yes to what matters.",
  dd12: "Excuses are easy. Results need repetitions.",
  dd13: "Pick one priority and defend it.",
  dd14: "Gotta make it happen.",
  dd15: "Plan B is just plan A with more time.",
  dd16: "Dreaming and taking action are two different things.",
  dd17: "Don't wait to be lucky. Make your own luck.",
  dd18: "If you want it that bad, find a way. I trust you.",
  dd19: "The cheat code is discipline and consistency.",
  dd20: "Finish what you started.",
  dd21: "Make sure your time has high value.",
  dd22: "Time is non-refundable. Use it with intention.",
  dd23: "Act as if you already have it.",
  dd24: "If not now, then when?",
  dd25: "The next shot matters more than the last mistake.",
  dd26: "If someone else has it, why can't you?",
  dd27: "Be delusional about your goals.",
  dd28: "Don't be the obstacle to your own purpose.",
  dd29: "Everything you want is on the other side of fear.",
  dd30: "You were born ready.",
  // discipline · hard
  dh01: "Nobody is coming to do it for you.",
  dh02: "You said you would. So do it.",
  dh03: "Comfort today, regret tomorrow. Choose.",
  dh04: "No excuses. Not today.",
  dh05: "The clock doesn't wait for your mood. Get to work.",
  dh06: "Wanting it isn't enough. Earn it.",
  dh07: "Stop scrolling. Start doing.",
  dh08: "Every delay is a decision. Make a better one.",
  dh09: "Work beats talk. Every single time.",
  dh10: "You know exactly what to do. Go.",
  dh11: "Discipline now, or disappointment later.",
  dh12: "\"Tomorrow\" is where plans go to die. Act today.",
  dh13: "The work won't do itself. Neither will the change.",
  dh14: "All in.",
  dh15: "Big dreams require big sacrifices.",
  dh16: "Either increase the sacrifice or reduce the desire.",
  dh17: "Play to win.",
  dh18: "Take so many losses that wins don't even surprise you anymore.",
  dh19: "Manifesting is pointless. Take action.",
  dh20: "Worst case, you make it. Best case, you make it bigger.",
  dh21: "You weren't born to be average.",
  dh22: "To get what you never had, do what you've never done.",
  dh23: "Not even the sky can limit you. Aim higher.",
  dh24: "The higher up the mountain, the more treacherous the path.",
  dh25: "Win in the no-win situation.",
  dh26: "Truth is, nobody is coming to save you.",
  dh27: "If people don't laugh at your goals, your goals are too small.",
  dh28: "The world makes waves. Surf or drown: you decide.",
  dh29: "No risk, no reward.",
  // habits · soft
  hs01: "A habit is a choice you repeat with kindness.",
  hs02: "Make it so small you can't say no.",
  hs03: "Same time, same place: let routine carry you.",
  hs04: "Missing once is human. Coming back is the habit.",
  hs05: "Celebrate the small wins: they build the big ones.",
  hs06: "Your surroundings can do half the work. Set them up.",
  hs07: "Tie a new habit to something you already do.",
  hs08: "Progress you can repeat beats progress you can't.",
  hs09: "Tonight, prepare one thing for tomorrow morning.",
  hs10: "Habits grow quietly, like plants. Keep watering.",
  hs11: "One good habit makes the next one easier.",
  hs12: "Notice what you do on autopilot. Choose one thing to improve.",
  hs13: "Begin where you are, with what you have.",
  hs14: "Morning walk?",
  hs15: "Take time to think.",
  hs16: "Seek knowledge.",
  hs17: "Spend more time getting to know yourself, less absorbing everyone around you.",
  hs18: "Trying is already an act of change.",
  // habits · direct
  hd01: "Your days are built from habits. Build better days.",
  hd02: "Never skip twice in a row.",
  hd03: "Keep track of it, or you'll end up telling yourself stories.",
  hd04: "Make the right choice the easy one.",
  hd05: "Remove one trigger of the habit you want to drop.",
  hd06: "Repetition beats intensity.",
  hd07: "If it's not on your calendar, it's just a wish.",
  hd08: "Small actions every day, big results in a year.",
  hd09: "Rough day? Do the minimum version. It still counts.",
  hd10: "Your phone is a habit too. Decide who's in charge.",
  hd11: "Show up first. Improve later.",
  hd12: "Stack small wins before noon.",
  hd13: "What you repeat, you become.",
  hd14: "Lock in, for you.",
  hd15: "Evolve or repeat.",
  hd16: "Break the pattern.",
  hd17: "Momentum corrects mistakes faster than regret will.",
  hd18: "Don't act on impulse.",
  hd19: "The fastest way to kill an idea is asking ten people what they think.",
  hd20: "Life isn't meant to be lived standing still. Keep moving.",
  hd21: "If you chop your own wood, it warms you twice.",
  hd22: "Ugh, I hate boring things. Don't you?",
  // habits · hard
  hh01: "Your habits are voting for your future. Check the count.",
  hh02: "Every \"just this once\" is a habit in disguise.",
  hh03: "You don't lack time. You lack a routine.",
  hh04: "Break the streak of excuses, not the streak of work.",
  hh05: "Same habits, same results. Change something.",
  hh06: "Stop hitting snooze. Win the first minute.",
  hh07: "Two skipped days is how quitting starts. Get back today.",
  hh08: "The habit you're avoiding is the one you need.",
  hh09: "Stop starting over. Keep going.",
  hh10: "If you keep doing it, you're choosing it.",
  hh11: "Routine isn't boring. Chaos is expensive.",
  hh12: "Delete the distraction. Today, not tomorrow.",
  hh13: "Good intentions without habits are just noise.",
  hh14: "You know your next step. You're just hoping for an easier one.",
  // character · soft
  cs01: "Kindness and strength can live together.",
  cs02: "Keep small promises to yourself. They turn into trust.",
  cs03: "You can be patient with yourself and still aim high.",
  cs04: "Honesty starts with what you tell yourself.",
  cs05: "Do the right thing, even when no one is watching.",
  cs06: "Courage is often a quiet \"I'll try again\".",
  cs07: "Your values are a compass. Look at it today.",
  cs08: "Listen more than you speak today.",
  cs09: "Gratitude makes the ordinary feel like enough.",
  cs10: "Asking for help is fine. That's strength too.",
  cs11: "Treating others with care shapes who you become.",
  cs12: "The effort deserves pride, not only the result.",
  cs13: "Grow at your own pace. Comparison isn't a map.",
  cs14: "What's your philosophy, exactly?",
  cs15: "Just like money, emotions are an investment too.",
  cs16: "Inside, you are more.",
  cs17: "Believing in yourself costs nothing. Confidence is free.",
  cs18: "The blueprint is believing in yourself.",
  cs19: "Be a mystery.",
  cs20: "Life is a mirror of the mind.",
  cs21: "Dress simply, for yourself, not to impress.",
  cs22: "Be brave enough to be bad at something new.",
  cs23: "What is it about love that makes us lose our minds?",
  // character · direct
  cd01: "Character is what you do when it's inconvenient.",
  cd02: "Own your mistakes. Then fix them.",
  cd03: "Say what you mean. Do what you say.",
  cd04: "Respect is earned in small moments.",
  cd05: "Be on time: it tells people they matter.",
  cd06: "When right and easy split, pick right.",
  cd07: "Complaining changes nothing. Action does.",
  cd08: "Your word is a contract. Honor it.",
  cd09: "Become the person your plans need.",
  cd10: "Admit what you don't know. Then learn it.",
  cd11: "Calm is a skill. Practice it today.",
  cd12: "Clarity without harshness, firmness without coldness.",
  cd13: "Integrity means doing it right when shortcuts are easy.",
  cd14: "Never tell anyone your dreams.",
  cd15: "Own yourself, and only yourself.",
  cd16: "Trust actions more than words.",
  cd17: "It's okay to be angry. It's never okay to be cruel.",
  cd18: "Choices made in anger can't be undone.",
  cd19: "You are the first victim of your own anger.",
  cd20: "Made a mistake? Apologize.",
  cd21: "Miss someone? Speak up.",
  cd22: "In love? Say it.",
  cd23: "Don't play hard to get. You only live once.",
  cd24: "Disagree if you need to. It's your opinion.",
  cd25: "Care about your character, not your reputation: one is who you are, the other is what people think.",
  cd26: "Trust your gut.",
  cd27: "Sometimes you have to trust your own thinking more than anyone around you.",
  cd28: "Believe in hate at first sight the way you believe in love at first sight.",
  cd29: "Not everyone will see your vision. Keep going.",
  cd30: "You never needed to believe it to have permission to try.",
  cd31: "Action cures fear.",
  // character · hard
  ch01: "Stop blaming. Start owning it.",
  ch02: "Talk is cheap. Show it.",
  ch03: "If it matters to you, prove it today.",
  ch04: "Nobody owes you a shortcut.",
  ch05: "Honest question: are you busy, or avoiding something?",
  ch06: "Excuses don't change results.",
  ch07: "Keep your word, especially to yourself.",
  ch08: "Fear gets a vote, not a veto.",
  ch09: "Don't wait for courage. Act, and it will come.",
  ch10: "Raise the bar. Then stay there.",
  ch11: "Responsibility isn't a burden. It's power.",
  ch12: "Stop asking if it's fair. Ask what's next.",
  ch13: "Pressure shows who you are. Prepare now.",
  ch14: "Let them think whatever the hell they want.",
  ch15: "Critics? Not your problem.",
  ch16: "Make a fool of yourself. Be you.",
  ch17: "Post it, and don't be scared of what others think.",
  ch18: "The fact is, you don't need anything from anyone.",
  ch19: "If they don't recognize you, it means you're making progress.",
  ch20: "They have no idea who you're going to become.",
  ch21: "You are your worst fear and your best fantasy.",
  ch22: "You can travel anywhere in the world, but you can't escape yourself.",
  ch23: "In a room full of mirrors, you'd be surrounded by winners.",
  ch24: "Make choices and don't look back.",
  ch25: "Just make sure you rise above all this madness.",
  ch26: "Birds born in a cage think flying is an illness.",
  ch27: "Smart people know what they are.",
  ch28: "Choose your scandal and your success.",
  ch29: "No offence, but wow.",
  ch30: "Nyah nyah.",
  ch31: "The thing about common sense? It's so… common.",
  // recovery · soft
  rs01: "Rest is part of the work, not a break from it.",
  rs02: "Even on a slow day, you showed up. That's enough.",
  rs03: "Breathe out. You don't have to do everything today.",
  rs04: "Setbacks are part of the path, not the end of it.",
  rs05: "Sleep well tonight. Tomorrow will thank you.",
  rs06: "Be as kind to yourself as you'd be to someone you love.",
  rs07: "It's fine to pause. Just remember to come back.",
  rs08: "Today the goal is to recover. That's allowed.",
  rs09: "Take a short walk, look at the sky, start again.",
  rs10: "You've handled hard days before. You'll handle this one.",
  rs11: "Let go of yesterday. Today is a new page.",
  rs12: "A reset isn't a failure. It's maintenance.",
  rs13: "Quiet minutes are how energy comes back.",
  rs14: "Take time to heal.",
  rs15: "Joy has a habit of returning.",
  rs16: "It will make sense later.",
  rs17: "Let it happen.",
  rs18: "Let the light in.",
  rs19: "Someday, somehow.",
  rs20: "Even what's broken lets the light through.",
  rs21: "A step backward is still part of the dance.",
  rs22: "Losing something isn't always a loss.",
  rs23: "Sometimes good, sometimes bad. Things come, things go.",
  rs24: "Don't forget you're part of nature too.",
  rs25: "People can be museums too, full of history they can no longer touch.",
  rs26: "You can be anything, do anything, start over.",
  rs27: "It's okay to leave behind what doesn't feel right, even if it's all you've ever known.",
  rs28: "Do it for you, and for all the nights you only had you.",
  rs29: "If you want peace, find it with yourself or with someone who thinks like you.",
  rs30: "Yay, hooray, bye, thanks!",
  rs31: "Idk, time for the et cetera.",
  rs32: "Have a good night, and stay hydrated.",
  // recovery · direct
  rd01: "A slip. Fine. Next step.",
  rd02: "Rest on purpose, not by collapse.",
  rd03: "Lost a day? Don't lose the week.",
  rd04: "Recover, then return. In that order.",
  rd05: "Bad moments don't make a bad life.",
  rd06: "Keep the lesson, drop the guilt.",
  rd07: "Turn off the screen an hour earlier tonight.",
  rd08: "A break is a tool. Use it, then get back.",
  rd09: "Missed the plan? Make a smaller one and keep it.",
  rd10: "Everything stuck? Change one thing, then look again.",
  rd11: "Tiredness is information, not an excuse.",
  rd12: "Restart today. Not on Monday.",
  rd13: "Too much to do? Write down the next tiny step.",
  rd14: "Sometimes the only progress is not giving up.",
  rd15: "The less you worry, the more you live.",
  rd16: "Living well is the best revenge.",
  rd17: "Learn to enjoy life without needing an audience.",
  rd18: "Anything lost can be found again, except wasted time.",
  rd19: "A positive mindset makes a difference, not the difference.",
  rd20: "Freedom starts when you realize the cage is made of thoughts.",
  rd21: "Disappear for a while, and come back with more momentum.",
  rd22: "Don't look back. You're not going that way.",
  rd23: "The past is out of your hands. The future is in them.",
  rd24: "Be a little selfish with your time.",
  // recovery · hard
  rh01: "Fall, get up. No speeches.",
  rh02: "Self-pity wastes the time you need to recover.",
  rh03: "Yesterday is over. Stop replaying it.",
  rh04: "One bad day is an event. Two is a choice.",
  rh05: "Rest, yes. Hide, no.",
  rh06: "You've started again before. Do it again, now.",
  rh07: "Setback? Good. Now you know what to fix.",
  rh08: "Don't wait for a perfect restart. Take the imperfect one.",
  rh09: "Get back in the game. The bench isn't your seat.",
  rh10: "Recover for real, then come back at full pace.",
  rh11: "Mistakes are paid with action, not guilt.",
  rh12: "The comeback starts with the next small move.",
  rh13: "No drama. Reset and go.",
  rh14: "Womp womp. Next.",
};
