import type { QuoteTexts } from "./types";

export const es: QuoteTexts = {
  // discipline · soft
  ds01: "Los pasos pequeños también te llevan adelante.",
  ds02: "No hace falta esperar el momento perfecto. Empieza con calma.",
  ds03: "Hacer un poco hoy vale más que planear mucho.",
  ds04: "La constancia es un regalo para quien serás mañana.",
  ds05: "Una hora de concentración puede cambiar la forma de un día.",
  ds06: "Cumple la promesa de esta mañana, aunque sea pequeña.",
  ds07: "La disciplina puede ser silenciosa. Simplemente vuelve a aparecer.",
  ds08: "Empieza por el paso más fácil. El impulso hará el resto.",
  ds09: "Se puede ir despacio y llegar lejos.",
  ds10: "Termina una cosa antes de empezar la siguiente.",
  ds11: "Un plan claro hace más ligeras las cosas difíciles.",
  ds12: "Hoy cuenta, aunque no sea perfecto.",
  ds13: "Protege tu atención: ahí vive tu día.",
  ds14: "Crea algo.",
  ds15: "Empieza y ya. Lo resolverás por el camino.",
  ds16: "No tengas prisa en la subida.",
  ds17: "Quizá no pase de la noche a la mañana, pero si lo dejas no pasará nunca.",
  ds18: "Se trata solo de tener claro lo que quieres.",
  ds19: "Cumple tus sueños. Con cariño, GetControl.",
  ds20: "Esto acaba de empezar.",
  ds21: "Existes para crear.",
  ds22: "Cuando la ilusión supera un poco al miedo, es hora de empezar.",
  ds23: "Las posibilidades no tienen fin.",
  // discipline · direct
  dd01: "La motivación va y viene. Hazlo igual.",
  dd02: "Decide una vez y deja de darle vueltas.",
  dd03: "Suelta el móvil y empieza.",
  dd04: "Un plan solo funciona si te mueves.",
  dd05: "Diez minutos ahora valen más que una hora \"algún día\".",
  dd06: "Hecho es mejor que perfecto. Ciérralo.",
  dd07: "Tu agenda muestra tus prioridades. Revísala.",
  dd08: "Deja de esperar el ánimo perfecto. Ponte a trabajar.",
  dd09: "Haz primero lo difícil, mientras tienes energía.",
  dd10: "Si lleva dos minutos, hazlo ahora.",
  dd11: "Hoy di que no a algo, para decir que sí a lo que importa.",
  dd12: "Las excusas son fáciles. Los resultados piden repeticiones.",
  dd13: "Elige una prioridad y defiéndela.",
  dd14: "Hay que hacer que pase.",
  dd15: "El plan B es solo el plan A con más tiempo.",
  dd16: "Soñar y actuar son dos cosas distintas.",
  dd17: "No esperes a tener suerte. Fabrícala.",
  dd18: "Si lo quieres tanto, encuentra la forma. Confío en ti.",
  dd19: "El truco es disciplina y constancia.",
  dd20: "Termina lo que empezaste.",
  dd21: "Haz que tu tiempo valga mucho.",
  dd22: "El tiempo no se devuelve. Úsalo con intención.",
  dd23: "Actúa como si ya lo tuvieras.",
  dd24: "Si no es ahora, ¿cuándo?",
  dd25: "El próximo tiro importa más que el último error.",
  dd26: "Si alguien lo tiene, ¿por qué tú no?",
  dd27: "Cree en tus metas de forma exagerada.",
  dd28: "No seas el obstáculo de tu propio propósito.",
  dd29: "Todo lo que quieres está al otro lado del miedo.",
  dd30: "Naciste con todo lo necesario.",
  // discipline · hard
  dh01: "Nadie va a venir a hacerlo por ti.",
  dh02: "Dijiste que lo harías. Pues hazlo.",
  dh03: "Comodidad hoy, arrepentimiento mañana. Elige.",
  dh04: "Sin excusas. Hoy no.",
  dh05: "El reloj no espera a tu humor. A trabajar.",
  dh06: "Quererlo no basta. Gánatelo.",
  dh07: "Deja de hacer scroll. Empieza a hacer.",
  dh08: "Cada retraso es una decisión. Toma una mejor.",
  dh09: "El trabajo gana a la charla. Siempre.",
  dh10: "Sabes exactamente qué hacer. Vamos.",
  dh11: "Disciplina ahora o decepción después.",
  dh12: "\"Mañana\" es donde los planes van a morir. Actúa hoy.",
  dh13: "El trabajo no se hace solo. El cambio tampoco.",
  dh14: "Con todo.",
  dh15: "Los grandes sueños piden grandes sacrificios.",
  dh16: "O aumentas el sacrificio, o reduces el deseo.",
  dh17: "Juega para ganar.",
  dh18: "Acumula tantas derrotas que las victorias ya no te sorprendan.",
  dh19: "Manifestar no sirve. Actúa.",
  dh20: "En el peor caso, lo logras. En el mejor, lo logras a lo grande.",
  dh21: "No viniste al mundo para ser del montón.",
  dh22: "Para tener lo que nunca tuviste, haz lo que nunca hiciste.",
  dh23: "Ni el cielo te limita. Apunta más alto.",
  dh24: "Cuanto más alto en la montaña, más traicionero el camino.",
  dh25: "Gana en la situación imposible.",
  dh26: "La verdad: nadie va a venir a salvarte.",
  dh27: "Si nadie se ríe de tus metas, son demasiado pequeñas.",
  dh28: "El mundo hace olas. Surfea o húndete: tú decides.",
  dh29: "Sin riesgo no hay recompensa.",
  // habits · soft
  hs01: "Un hábito es una elección que repites con amabilidad.",
  hs02: "Hazlo tan pequeño que no puedas decir que no.",
  hs03: "Misma hora, mismo lugar: deja que la rutina te lleve.",
  hs04: "Fallar una vez es humano. Volver es el hábito.",
  hs05: "Celebra las pequeñas victorias: construyen las grandes.",
  hs06: "Tu entorno puede hacer la mitad del trabajo. Prepáralo.",
  hs07: "Ata un hábito nuevo a algo que ya haces.",
  hs08: "Un progreso que puedes repetir vale más que uno que no.",
  hs09: "Esta noche, prepara una cosa para mañana por la mañana.",
  hs10: "Los hábitos crecen en silencio, como las plantas. Sigue regando.",
  hs11: "Un buen hábito hace más fácil el siguiente.",
  hs12: "Fíjate en lo que haces en piloto automático. Elige una cosa que mejorar.",
  hs13: "Empieza donde estás, con lo que tienes.",
  hs14: "¿Paseo por la mañana?",
  hs15: "Tómate tiempo para pensar.",
  hs16: "Busca conocimiento.",
  hs17: "Pasa más tiempo conociéndote y menos absorbiendo a todos los demás.",
  hs18: "Intentarlo ya es un acto de cambio.",
  // habits · direct
  hd01: "Tus días están hechos de hábitos. Construye días mejores.",
  hd02: "Nunca te saltes dos veces seguidas.",
  hd03: "Llévalo apuntado, o acabarás contándote historias.",
  hd04: "Haz que la buena elección sea la fácil.",
  hd05: "Quita un detonante del hábito que quieres dejar.",
  hd06: "La repetición gana a la intensidad.",
  hd07: "Si no está en tu agenda, es solo un deseo.",
  hd08: "Pequeñas acciones cada día, grandes resultados en un año.",
  hd09: "¿Día torcido? Haz la versión mínima. También cuenta.",
  hd10: "El móvil también es un hábito. Decide quién manda.",
  hd11: "Primero preséntate. Luego mejora.",
  hd12: "Acumula pequeñas victorias antes del mediodía.",
  hd13: "Te conviertes en lo que repites.",
  hd14: "Concéntrate, por ti.",
  hd15: "Evoluciona o repite.",
  hd16: "Rompe el patrón.",
  hd17: "El impulso corrige errores más rápido que el arrepentimiento.",
  hd18: "No actúes por impulso.",
  hd19: "La forma más rápida de matar una idea es preguntar a diez personas qué opinan.",
  hd20: "La vida no está hecha para quedarse quieta. Muévete, siempre.",
  hd21: "Si cortas tu propia leña, te calienta dos veces.",
  hd22: "Uf, odio las cosas aburridas. ¿Tú no?",
  // habits · hard
  hh01: "Tus hábitos votan por tu futuro. Revisa el recuento.",
  hh02: "Cada \"solo esta vez\" es un hábito disfrazado.",
  hh03: "No te falta tiempo. Te falta una rutina.",
  hh04: "Rompe la racha de excusas, no la de trabajo.",
  hh05: "Mismos hábitos, mismos resultados. Cambia algo.",
  hh06: "Deja de posponer la alarma. Gana el primer minuto.",
  hh07: "Dos días saltados son el comienzo del abandono. Vuelve hoy.",
  hh08: "El hábito que estás evitando es el que necesitas.",
  hh09: "Deja de empezar de cero. Sigue.",
  hh10: "Si lo sigues haciendo, lo estás eligiendo.",
  hh11: "La rutina no es aburrida. El caos sale caro.",
  hh12: "Elimina la distracción. Hoy, no mañana.",
  hh13: "Las buenas intenciones sin hábitos son solo ruido.",
  hh14: "Conoces tu siguiente paso. Solo esperas que haya uno más fácil.",
  // character · soft
  cs01: "La amabilidad y la fuerza pueden convivir.",
  cs02: "Cumple las pequeñas promesas que te haces: se convierten en confianza.",
  cs03: "Puedes tener paciencia contigo y apuntar alto.",
  cs04: "La honestidad empieza por lo que te cuentas a ti.",
  cs05: "Haz lo correcto aunque nadie mire.",
  cs06: "El valor muchas veces es un \"lo vuelvo a intentar\" en voz baja.",
  cs07: "Tus valores son una brújula. Mírala hoy.",
  cs08: "Hoy escucha más de lo que hablas.",
  cs09: "La gratitud hace que lo cotidiano sea suficiente.",
  cs10: "Pedir ayuda está bien. También eso es fuerza.",
  cs11: "Tratar a los demás con cuidado da forma a quien llegas a ser.",
  cs12: "El esfuerzo merece orgullo, no solo el resultado.",
  cs13: "Crece a tu ritmo. Compararte no es un mapa.",
  cs14: "¿Cuál es tu filosofía, exactamente?",
  cs15: "Como el dinero, las emociones también son una inversión.",
  cs16: "Por dentro eres más.",
  cs17: "Creer en ti no cuesta nada. La confianza es gratis.",
  cs18: "El plan empieza por creer en ti.",
  cs19: "Sé un misterio.",
  cs20: "La vida es un espejo de la mente.",
  cs21: "Vístete sencillo, para ti, no para impresionar.",
  cs22: "Ten el valor de hacer mal algo nuevo.",
  cs23: "¿Qué tiene el amor que nos hace perder la cabeza?",
  // character · direct
  cd01: "El carácter es lo que haces cuando no te conviene.",
  cd02: "Reconoce tus errores. Luego arréglalos.",
  cd03: "Di lo que piensas. Haz lo que dices.",
  cd04: "El respeto se gana en los pequeños momentos.",
  cd05: "Sé puntual: les dice a los demás que importan.",
  cd06: "Cuando lo correcto y lo cómodo se separan, elige lo correcto.",
  cd07: "Quejarse no cambia nada. Actuar sí.",
  cd08: "Tu palabra es un contrato. Cúmplela.",
  cd09: "Conviértete en la persona que tus planes necesitan.",
  cd10: "Admite lo que no sabes. Luego apréndelo.",
  cd11: "La calma es una habilidad. Practícala hoy.",
  cd12: "Claridad sin dureza, firmeza sin frialdad.",
  cd13: "Integridad es hacerlo bien cuando los atajos son fáciles.",
  cd14: "No le cuentes a nadie tus sueños.",
  cd15: "Te perteneces a ti, y solo a ti.",
  cd16: "Fíate más de los hechos que de las palabras.",
  cd17: "Enfadarse está bien. Ser cruel, nunca.",
  cd18: "Las decisiones tomadas con rabia no se pueden deshacer.",
  cd19: "La primera víctima de tu rabia eres tú.",
  cd20: "¿Te has equivocado? Pide perdón.",
  cd21: "¿Echas de menos a alguien? Díselo.",
  cd22: "¿Sientes amor? Dilo.",
  cd23: "No te hagas de rogar: solo se vive una vez.",
  cd24: "Si hace falta, discrepa: es tu opinión.",
  cd25: "Cuida tu carácter, no tu reputación: uno es quién eres, la otra lo que piensan los demás.",
  cd26: "Fíate de tu instinto.",
  cd27: "A veces tienes que fiarte de tu cabeza más que de cualquiera a tu alrededor.",
  cd28: "Cree en la antipatía a primera vista como crees en el amor a primera vista.",
  cd29: "No todos verán tu visión. Sigue.",
  cd30: "No hace falta creerlo para tener permiso de intentarlo.",
  cd31: "La acción cura el miedo.",
  // character · hard
  ch01: "Deja de culpar. Hazte responsable.",
  ch02: "Hablar es fácil. Demuéstralo.",
  ch03: "Si te importa, demuéstralo hoy.",
  ch04: "Nadie te debe un atajo.",
  ch05: "Pregunta sincera: ¿tienes mucho que hacer o estás evitando algo?",
  ch06: "Las excusas no cambian los resultados.",
  ch07: "Cumple tu palabra, sobre todo contigo.",
  ch08: "El miedo tiene voto, pero no veto.",
  ch09: "No esperes al valor. Actúa y llegará.",
  ch10: "Sube el listón. Y quédate ahí.",
  ch11: "La responsabilidad no es una carga. Es poder.",
  ch12: "Deja de preguntar si es justo. Pregunta qué sigue.",
  ch13: "La presión muestra quién eres. Prepárate ahora.",
  ch14: "Que piensen lo que les dé la gana.",
  ch15: "¿Las críticas? No son tu problema.",
  ch16: "No temas hacer el ridículo. Sé tú.",
  ch17: "Publícalo, y no tengas miedo de lo que piensen.",
  ch18: "La verdad es que no necesitas nada de nadie.",
  ch19: "Si no te reconocen, es que estás avanzando.",
  ch20: "No tienen ni idea de en quién te vas a convertir.",
  ch21: "Eres tu peor miedo y tu mejor fantasía.",
  ch22: "Puedes viajar a cualquier parte del mundo, pero no puedes escapar de ti.",
  ch23: "En una habitación llena de espejos, solo verías ganadores.",
  ch24: "Toma decisiones y no mires atrás.",
  ch25: "Solo asegúrate de estar por encima de toda esta locura.",
  ch26: "Los pájaros nacidos en jaula creen que volar es una enfermedad.",
  ch27: "La gente lista sabe lo que es.",
  ch28: "Elige tu escándalo y tu éxito.",
  ch29: "Sin ofender, pero guau.",
  ch30: "Chincha, rabiña.",
  ch31: "¿Lo del sentido común? Es tan… común.",
  // recovery · soft
  rs01: "El descanso es parte del trabajo, no una pausa del trabajo.",
  rs02: "Incluso en un día lento, estás aquí. Y basta.",
  rs03: "Suelta el aire. No tienes que hacerlo todo hoy.",
  rs04: "Los tropiezos son parte del camino, no su final.",
  rs05: "Duerme bien esta noche. Mañana te lo agradecerá.",
  rs06: "Trátate con la amabilidad con la que tratarías a alguien que quieres.",
  rs07: "Parar está bien. Solo recuerda volver.",
  rs08: "Hoy el objetivo es recuperarse. Está permitido.",
  rs09: "Da un paseo corto, mira el cielo, vuelve a empezar.",
  rs10: "Ya has superado días difíciles. También superarás este.",
  rs11: "Suelta el ayer. Hoy es una página nueva.",
  rs12: "Reiniciar no es fracasar. Es mantenimiento.",
  rs13: "Los minutos de calma son la forma en que vuelve la energía.",
  rs14: "Tómate tiempo para sanar.",
  rs15: "La alegría tiene la costumbre de volver.",
  rs16: "Más adelante tendrá sentido.",
  rs17: "Deja que pase.",
  rs18: "Deja entrar la luz.",
  rs19: "Algún día, de alguna forma.",
  rs20: "Hasta lo que está roto deja pasar la luz.",
  rs21: "Un paso atrás también forma parte del baile.",
  rs22: "Perder algo no siempre es una pérdida.",
  rs23: "A veces bien, a veces mal. Las cosas vienen y van.",
  rs24: "No olvides que tú también formas parte de la naturaleza.",
  rs25: "Las personas también pueden ser museos, llenos de historia que ya no pueden tocar.",
  rs26: "Puedes ser lo que quieras, hacer lo que quieras, volver a empezar.",
  rs27: "Está bien dejar atrás lo que no te hace bien, aunque sea todo lo que has conocido.",
  rs28: "Hazlo por ti, y por todas las noches en que solo te tenías a ti.",
  rs29: "Si quieres paz, búscala contigo o con quien piense como tú.",
  rs30: "¡Yupi, hurra, adiós, gracias!",
  rs31: "Ni idea, hora del etcétera.",
  rs32: "Buenas noches, y bebe agua.",
  // recovery · direct
  rd01: "Un tropiezo. Vale. Siguiente paso.",
  rd02: "Descansa por elección, no porque te derrumbes.",
  rd03: "¿Has perdido un día? No pierdas la semana.",
  rd04: "Primero recupérate, luego vuelve. En ese orden.",
  rd05: "Los malos momentos no hacen una mala vida.",
  rd06: "Quédate con la lección, suelta la culpa.",
  rd07: "Esta noche apaga la pantalla una hora antes.",
  rd08: "Una pausa es una herramienta. Úsala y vuelve.",
  rd09: "¿Plan saltado? Haz uno más pequeño y cúmplelo.",
  rd10: "¿Todo atascado? Cambia una cosa y vuelve a mirar.",
  rd11: "El cansancio es información, no una excusa.",
  rd12: "Vuelve a empezar hoy. No el lunes.",
  rd13: "¿Demasiado que hacer? Escribe el próximo paso diminuto.",
  rd14: "A veces el único progreso es no rendirse.",
  rd15: "Cuanto menos te preocupas, más vives.",
  rd16: "Vivir bien es la mejor venganza.",
  rd17: "Aprende a disfrutar la vida sin necesitar público.",
  rd18: "Todo lo perdido se puede encontrar, menos el tiempo malgastado.",
  rd19: "Una mentalidad positiva marca una diferencia, no la diferencia.",
  rd20: "La libertad empieza cuando ves que la jaula está hecha de pensamientos.",
  rd21: "Desaparece un tiempo y vuelve con más impulso.",
  rd22: "No mires atrás: no vas en esa dirección.",
  rd23: "El pasado ya no está en tus manos. El futuro, sí.",
  rd24: "Sé un poco egoísta con tu tiempo.",
  // recovery · hard
  rh01: "Caes, te levantas. Sin discursos.",
  rh02: "Compadecerse malgasta el tiempo que necesitas para recuperarte.",
  rh03: "Ayer ya pasó. Deja de repetirlo.",
  rh04: "Un mal día es un accidente. Dos son una elección.",
  rh05: "Descansar, sí. Esconderse, no.",
  rh06: "Ya has vuelto a empezar otras veces. Hazlo otra vez, ahora.",
  rh07: "¿Un revés? Bien. Ahora sabes qué arreglar.",
  rh08: "No esperes el reinicio perfecto. Toma el imperfecto.",
  rh09: "Vuelve al juego. El banquillo no es tu sitio.",
  rh10: "Recupérate de verdad y vuelve a pleno ritmo.",
  rh11: "Los errores se pagan con hechos, no con culpa.",
  rh12: "La remontada empieza con el próximo pequeño movimiento.",
  rh13: "Sin dramas. Reinicia y adelante.",
  rh14: "Womp womp. Siguiente.",
};
