import type { QuoteTexts } from "./types";

export const fr: QuoteTexts = {
  // discipline · soft
  ds01: "Les petits pas te font avancer aussi.",
  ds02: "Pas besoin d'attendre le bon moment. Commence en douceur.",
  ds03: "En faire un peu aujourd'hui vaut mieux que beaucoup planifier.",
  ds04: "La régularité est un cadeau pour la personne que tu seras demain.",
  ds05: "Une heure de concentration peut changer la forme d'une journée.",
  ds06: "Tiens la promesse de ce matin, même si elle est petite.",
  ds07: "La discipline peut être silencieuse. Elle revient, tout simplement.",
  ds08: "Commence par l'étape la plus facile. L'élan fera le reste.",
  ds09: "On peut aller lentement et aller loin.",
  ds10: "Finis une chose avant d'en commencer une autre.",
  ds11: "Un plan clair rend les choses difficiles plus légères.",
  ds12: "Aujourd'hui compte, même s'il n'est pas parfait.",
  ds13: "Protège ton attention : c'est là que vit ta journée.",
  ds14: "Crée quelque chose.",
  ds15: "Commence, c'est tout. Tu trouveras en chemin.",
  ds16: "Ne te presse pas dans la montée.",
  ds17: "Ça n'arrivera peut-être pas du jour au lendemain, mais si tu abandonnes, ça n'arrivera jamais.",
  ds18: "Il s'agit juste de savoir clairement ce que tu veux.",
  ds19: "Réalise tes rêves. Avec affection, GetControl.",
  ds20: "On ne fait que commencer.",
  ds21: "Tu existes pour créer.",
  ds22: "Quand l'envie dépasse un peu la peur, c'est le moment de commencer.",
  ds23: "Les possibilités sont infinies.",
  // discipline · direct
  dd01: "La motivation va et vient. Fais-le quand même.",
  dd02: "Décide une fois, puis arrête de remettre ça en question.",
  dd03: "Pose le téléphone et commence.",
  dd04: "Un plan ne marche que si tu bouges.",
  dd05: "Dix minutes maintenant valent mieux qu'une heure « un jour ».",
  dd06: "Fait vaut mieux que parfait. Boucle-le.",
  dd07: "Ton agenda montre tes priorités. Vérifie-le.",
  dd08: "Arrête d'attendre la bonne humeur. Mets-toi au travail.",
  dd09: "Fais d'abord le plus dur, tant que tu as de l'énergie.",
  dd10: "Si ça prend deux minutes, fais-le maintenant.",
  dd11: "Dis non à quelque chose aujourd'hui, pour dire oui à ce qui compte.",
  dd12: "Les excuses, c'est facile. Les résultats demandent des répétitions.",
  dd13: "Choisis une priorité et défends-la.",
  dd14: "Il faut que ça se fasse.",
  dd15: "Le plan B, c'est juste le plan A avec plus de temps.",
  dd16: "Rêver et agir sont deux choses différentes.",
  dd17: "N'attends pas la chance. Fabrique-la.",
  dd18: "Si tu le veux à ce point, trouve un moyen. J'ai confiance en toi.",
  dd19: "Le code de triche, c'est discipline et régularité.",
  dd20: "Finis ce que tu as commencé.",
  dd21: "Fais en sorte que ton temps ait de la valeur.",
  dd22: "Le temps n'est pas remboursable. Utilise-le avec intention.",
  dd23: "Agis comme si tu l'avais déjà.",
  dd24: "Si ce n'est pas maintenant, quand ?",
  dd25: "Le prochain tir compte plus que la dernière erreur.",
  dd26: "Si quelqu'un l'a, pourquoi pas toi ?",
  dd27: "Crois à tes objectifs de façon démesurée.",
  dd28: "Ne sois pas l'obstacle à ton propre but.",
  dd29: "Tout ce que tu veux est de l'autre côté de la peur.",
  dd30: "Tu as tout ce qu'il faut depuis toujours.",
  // discipline · hard
  dh01: "Personne ne viendra le faire à ta place.",
  dh02: "Tu as dit que tu le ferais. Alors fais-le.",
  dh03: "Confort aujourd'hui, regrets demain. Choisis.",
  dh04: "Pas d'excuses. Pas aujourd'hui.",
  dh05: "L'horloge n'attend pas ton humeur. Au travail.",
  dh06: "Le vouloir ne suffit pas. Mérite-le.",
  dh07: "Arrête de scroller. Commence à faire.",
  dh08: "Chaque report est une décision. Prends-en une meilleure.",
  dh09: "Le travail bat les paroles. À chaque fois.",
  dh10: "Tu sais exactement quoi faire. Vas-y.",
  dh11: "La discipline maintenant, ou la déception plus tard.",
  dh12: "« Demain », c'est là que les projets vont mourir. Agis aujourd'hui.",
  dh13: "Le travail ne se fera pas tout seul. Le changement non plus.",
  dh14: "À fond.",
  dh15: "Les grands rêves demandent de grands sacrifices.",
  dh16: "Soit tu augmentes le sacrifice, soit tu réduis le désir.",
  dh17: "Joue pour gagner.",
  dh18: "Encaisse tant de défaites que les victoires ne te surprennent plus.",
  dh19: "Manifester ne sert à rien. Agis.",
  dh20: "Au pire, tu réussis. Au mieux, tu réussis en grand.",
  dh21: "Tu n'es pas là pour une vie moyenne.",
  dh22: "Pour avoir ce que tu n'as jamais eu, fais ce que tu n'as jamais fait.",
  dh23: "Même le ciel ne te limite pas. Vise plus haut.",
  dh24: "Plus on monte sur la montagne, plus le chemin est traître.",
  dh25: "Gagne dans la situation impossible.",
  dh26: "La vérité, c'est que personne ne viendra te sauver.",
  dh27: "Si personne ne rit de tes objectifs, ils sont trop petits.",
  dh28: "Le monde fait des vagues. Surfe ou coule : à toi de voir.",
  dh29: "Qui ne risque rien n'a rien.",
  // habits · soft
  hs01: "Une habitude, c'est un choix que tu répètes avec gentillesse.",
  hs02: "Rends-la si petite que tu ne peux pas dire non.",
  hs03: "Même heure, même endroit : laisse la routine te porter.",
  hs04: "Rater une fois, c'est humain. Revenir, c'est l'habitude.",
  hs05: "Fête les petites victoires : elles construisent les grandes.",
  hs06: "Ton environnement peut faire la moitié du travail. Prépare-le.",
  hs07: "Accroche une nouvelle habitude à quelque chose que tu fais déjà.",
  hs08: "Un progrès que tu peux répéter vaut mieux qu'un progrès qui ne revient pas.",
  hs09: "Ce soir, prépare une chose pour demain matin.",
  hs10: "Les habitudes poussent en silence, comme les plantes. Continue d'arroser.",
  hs11: "Une bonne habitude rend la suivante plus facile.",
  hs12: "Repère ce que tu fais en pilote automatique. Choisis une chose à améliorer.",
  hs13: "Commence là où tu es, avec ce que tu as.",
  hs14: "Une balade ce matin ?",
  hs15: "Prends le temps de réfléchir.",
  hs16: "Cherche le savoir.",
  hs17: "Passe plus de temps à te connaître et moins à absorber tout le monde autour.",
  hs18: "Essayer, c'est déjà changer.",
  // habits · direct
  hd01: "Tes journées sont faites d'habitudes. Construis de meilleures journées.",
  hd02: "Ne saute jamais deux fois de suite.",
  hd03: "Note-le, sinon tu finiras par te raconter des histoires.",
  hd04: "Rends le bon choix facile.",
  hd05: "Retire un déclencheur de l'habitude que tu veux lâcher.",
  hd06: "La répétition bat l'intensité.",
  hd07: "Si ce n'est pas dans ton agenda, c'est juste un souhait.",
  hd08: "De petites actions chaque jour, de grands résultats en un an.",
  hd09: "Journée difficile ? Fais la version minimum. Ça compte quand même.",
  hd10: "Ton téléphone aussi est une habitude. Décide qui commande.",
  hd11: "D'abord, sois là. Ensuite, progresse.",
  hd12: "Accumule de petites victoires avant midi.",
  hd13: "Tu deviens ce que tu répètes.",
  hd14: "Concentre-toi, pour toi.",
  hd15: "Évolue ou répète.",
  hd16: "Casse le schéma.",
  hd17: "L'élan corrige les erreurs plus vite que le regret.",
  hd18: "N'agis pas sur un coup de tête.",
  hd19: "Le moyen le plus rapide de tuer une idée, c'est de demander leur avis à dix personnes.",
  hd20: "La vie n'est pas faite pour rester immobile. Bouge, toujours.",
  hd21: "Si tu coupes ton propre bois, il te réchauffe deux fois.",
  hd22: "Pff, je déteste les choses ennuyeuses. Pas toi ?",
  // habits · hard
  hh01: "Tes habitudes votent pour ton avenir. Vérifie le décompte.",
  hh02: "Chaque « juste cette fois » est une habitude déguisée.",
  hh03: "Tu ne manques pas de temps. Tu manques de routine.",
  hh04: "Casse la série d'excuses, pas la série de travail.",
  hh05: "Mêmes habitudes, mêmes résultats. Change quelque chose.",
  hh06: "Arrête de repousser le réveil. Gagne la première minute.",
  hh07: "Deux jours sautés, c'est le début de l'abandon. Reprends aujourd'hui.",
  hh08: "L'habitude que tu évites est celle dont tu as besoin.",
  hh09: "Arrête de recommencer à zéro. Continue.",
  hh10: "Si tu continues à le faire, c'est que tu le choisis.",
  hh11: "La routine n'est pas ennuyeuse. Le chaos coûte cher.",
  hh12: "Supprime la distraction. Aujourd'hui, pas demain.",
  hh13: "Les bonnes intentions sans habitudes, c'est juste du bruit.",
  hh14: "Tu connais ta prochaine étape. Tu espères juste qu'il y en ait une plus facile.",
  // character · soft
  cs01: "La gentillesse et la force peuvent aller ensemble.",
  cs02: "Tiens les petites promesses que tu te fais : elles deviennent de la confiance.",
  cs03: "Tu peux avoir de la patience envers toi et viser haut.",
  cs04: "L'honnêteté commence par ce que tu te racontes.",
  cs05: "Fais ce qui est juste, même quand personne ne regarde.",
  cs06: "Le courage, c'est souvent un « je réessaie » à voix basse.",
  cs07: "Tes valeurs sont une boussole. Regarde-la aujourd'hui.",
  cs08: "Aujourd'hui, écoute plus que tu ne parles.",
  cs09: "La gratitude rend l'ordinaire suffisant.",
  cs10: "Demander de l'aide, c'est bien. C'est aussi de la force.",
  cs11: "Prendre soin des autres façonne la personne que tu deviens.",
  cs12: "L'effort mérite la fierté, pas seulement le résultat.",
  cs13: "Grandis à ton rythme. La comparaison n'est pas une carte.",
  cs14: "Quelle est ta philosophie, exactement ?",
  cs15: "Comme l'argent, les émotions sont aussi un investissement.",
  cs16: "À l'intérieur, tu es plus.",
  cs17: "Croire en toi ne coûte rien. La confiance est gratuite.",
  cs18: "Le plan commence par croire en toi.",
  cs19: "Sois un mystère.",
  cs20: "La vie est le miroir de l'esprit.",
  cs21: "Habille-toi simplement, pour toi, pas pour impressionner.",
  cs22: "Aie le courage de mal faire une chose nouvelle.",
  cs23: "Qu'a donc l'amour pour nous faire perdre la tête ?",
  // character · direct
  cd01: "Le caractère, c'est ce que tu fais quand ça ne t'arrange pas.",
  cd02: "Assume tes erreurs. Puis répare-les.",
  cd03: "Dis ce que tu penses. Fais ce que tu dis.",
  cd04: "Le respect se gagne dans les petits moments.",
  cd05: "Sois à l'heure : ça dit aux autres qu'ils comptent.",
  cd06: "Quand le juste et le facile se séparent, choisis le juste.",
  cd07: "Se plaindre ne change rien. Agir, si.",
  cd08: "Ta parole est un contrat. Respecte-la.",
  cd09: "Deviens la personne dont tes projets ont besoin.",
  cd10: "Admets ce que tu ne sais pas. Puis apprends-le.",
  cd11: "Le calme est une compétence. Entraîne-le aujourd'hui.",
  cd12: "La clarté sans dureté, la fermeté sans froideur.",
  cd13: "L'intégrité, c'est bien faire quand les raccourcis sont faciles.",
  cd14: "Ne raconte tes rêves à personne.",
  cd15: "Tu t'appartiens, et à personne d'autre.",
  cd16: "Fie-toi plus aux actes qu'aux mots.",
  cd17: "La colère, ça va. La cruauté, jamais.",
  cd18: "Les choix faits sous la colère ne se défont pas.",
  cd19: "La première victime de ta colère, c'est toi.",
  cd20: "Une erreur ? Excuse-toi.",
  cd21: "Quelqu'un te manque ? Dis-le-lui.",
  cd22: "Tu aimes ? Dis-le.",
  cd23: "Ne te fais pas désirer : on ne vit qu'une fois.",
  cd24: "Si besoin, ne sois pas d'accord : c'est ton avis.",
  cd25: "Soigne ton caractère, pas ta réputation : l'un est qui tu es, l'autre ce que les gens pensent.",
  cd26: "Fais confiance à ton instinct.",
  cd27: "Parfois, il faut te fier à ta tête plus qu'à n'importe qui autour de toi.",
  cd28: "Crois à l'antipathie au premier regard comme tu crois au coup de foudre.",
  cd29: "Tout le monde ne verra pas ta vision. Continue.",
  cd30: "Pas besoin d'y croire pour avoir le droit d'essayer.",
  cd31: "L'action guérit la peur.",
  // character · hard
  ch01: "Arrête d'accuser. Assume.",
  ch02: "Parler ne coûte rien. Prouve-le.",
  ch03: "Si ça compte pour toi, prouve-le aujourd'hui.",
  ch04: "Personne ne te doit un raccourci.",
  ch05: "Question honnête : tu as trop à faire, ou tu évites quelque chose ?",
  ch06: "Les excuses ne changent pas les résultats.",
  ch07: "Tiens parole, surtout envers toi.",
  ch08: "La peur a le droit de vote, pas de veto.",
  ch09: "N'attends pas le courage. Agis, il viendra.",
  ch10: "Place la barre plus haut. Puis restes-y.",
  ch11: "La responsabilité n'est pas un fardeau. C'est du pouvoir.",
  ch12: "Arrête de te demander si c'est juste. Demande-toi ce qui vient ensuite.",
  ch13: "La pression montre qui tu es. Prépare-toi maintenant.",
  ch14: "Qu'ils pensent ce qu'ils veulent, bon sang.",
  ch15: "Les critiques ? Pas ton problème.",
  ch16: "Ose le ridicule. Sois toi.",
  ch17: "Poste-le, et n'aie pas peur de ce que pensent les autres.",
  ch18: "En vrai, tu n'as besoin de rien de personne.",
  ch19: "S'ils ne te reconnaissent pas, c'est que tu progresses.",
  ch20: "Ils n'ont aucune idée de qui tu vas devenir.",
  ch21: "Tu es ta pire peur et ton plus beau fantasme.",
  ch22: "Tu peux voyager partout dans le monde, mais tu ne peux pas t'échapper à toi-même.",
  ch23: "Dans une pièce pleine de miroirs, tu ne verrais que des gagnants.",
  ch24: "Fais tes choix et ne regarde pas en arrière.",
  ch25: "Assure-toi juste de t'élever au-dessus de toute cette folie.",
  ch26: "Les oiseaux nés en cage croient que voler est une maladie.",
  ch27: "Les gens intelligents savent ce qu'ils sont.",
  ch28: "Choisis ton scandale et ton succès.",
  ch29: "Sans vouloir te vexer, mais wow.",
  ch30: "Nananère.",
  ch31: "Le sens commun ? Il est si… commun.",
  // recovery · soft
  rs01: "Le repos fait partie du travail, ce n'est pas une pause du travail.",
  rs02: "Même un jour au ralenti, tu es là. Et ça suffit.",
  rs03: "Expire. Tu n'as pas à tout faire aujourd'hui.",
  rs04: "Les faux pas font partie du chemin, pas sa fin.",
  rs05: "Dors bien cette nuit. Demain te remerciera.",
  rs06: "Traite-toi avec la douceur que tu offrirais à quelqu'un que tu aimes.",
  rs07: "Faire une pause, ça va. Pense juste à revenir.",
  rs08: "Aujourd'hui, l'objectif est de récupérer. C'est permis.",
  rs09: "Fais quelques pas, regarde le ciel, recommence.",
  rs10: "Tu as déjà traversé des jours difficiles. Tu traverseras celui-ci.",
  rs11: "Laisse partir hier. Aujourd'hui est une page blanche.",
  rs12: "Repartir n'est pas un échec. C'est de l'entretien.",
  rs13: "Les minutes de calme, c'est ainsi que l'énergie revient.",
  rs14: "Prends le temps de guérir.",
  rs15: "La joie a l'habitude de revenir.",
  rs16: "Ça aura du sens plus tard.",
  rs17: "Laisse faire.",
  rs18: "Laisse entrer la lumière.",
  rs19: "Un jour, d'une façon ou d'une autre.",
  rs20: "Même ce qui est cassé laisse passer la lumière.",
  rs21: "Un pas en arrière fait encore partie de la danse.",
  rs22: "Perdre quelque chose n'est pas toujours une perte.",
  rs23: "Parfois bien, parfois mal. Les choses viennent, les choses partent.",
  rs24: "N'oublie pas que tu fais partie de la nature, toi aussi.",
  rs25: "Les gens peuvent aussi être des musées, pleins d'histoires qu'ils ne peuvent plus toucher.",
  rs26: "Tu peux être n'importe quoi, faire n'importe quoi, recommencer.",
  rs27: "C'est bien de laisser derrière ce qui ne te fait pas du bien, même si c'est tout ce que tu as connu.",
  rs28: "Fais-le pour toi, et pour toutes les nuits où tu n'avais que toi.",
  rs29: "Si tu veux la paix, trouve-la avec toi ou avec quelqu'un qui pense comme toi.",
  rs30: "Youpi, hourra, salut, merci !",
  rs31: "Bof, c'est l'heure du et cetera.",
  rs32: "Bonne nuit, et bois de l'eau.",
  // recovery · direct
  rd01: "Un faux pas. D'accord. Étape suivante.",
  rd02: "Repose-toi par choix, pas par effondrement.",
  rd03: "Une journée perdue ? Ne perds pas la semaine.",
  rd04: "Récupère, puis reviens. Dans cet ordre.",
  rd05: "Les mauvais moments ne font pas une mauvaise vie.",
  rd06: "Garde la leçon, laisse la culpabilité.",
  rd07: "Ce soir, éteins l'écran une heure plus tôt.",
  rd08: "Une pause est un outil. Utilise-la, puis reviens.",
  rd09: "Plan raté ? Fais-en un plus petit et tiens-le.",
  rd10: "Tout est bloqué ? Change une chose, puis regarde à nouveau.",
  rd11: "La fatigue est une information, pas une excuse.",
  rd12: "Reprends aujourd'hui. Pas lundi.",
  rd13: "Trop de choses à faire ? Écris la prochaine toute petite étape.",
  rd14: "Parfois, le seul progrès, c'est de ne pas abandonner.",
  rd15: "Moins tu t'inquiètes, plus tu vis.",
  rd16: "Bien vivre est la meilleure des revanches.",
  rd17: "Apprends à profiter de la vie sans avoir besoin de public.",
  rd18: "Tout ce qui est perdu peut se retrouver, sauf le temps gâché.",
  rd19: "Un état d'esprit positif fait une différence, pas toute la différence.",
  rd20: "La liberté commence quand tu comprends que la cage est faite de pensées.",
  rd21: "Disparais un moment, et reviens avec plus d'élan.",
  rd22: "Ne regarde pas en arrière : ce n'est pas ta direction.",
  rd23: "Le passé n'est plus entre tes mains. L'avenir, si.",
  rd24: "Sois un peu égoïste avec ton temps.",
  // recovery · hard
  rh01: "Tu tombes, tu te relèves. Sans discours.",
  rh02: "S'apitoyer gaspille le temps qu'il te faut pour récupérer.",
  rh03: "Hier est fini. Arrête de le rejouer.",
  rh04: "Un mauvais jour, c'est un accident. Deux, c'est un choix.",
  rh05: "Se reposer, oui. Se cacher, non.",
  rh06: "Tu as déjà recommencé d'autres fois. Refais-le, maintenant.",
  rh07: "Un revers ? Bien. Maintenant tu sais quoi réparer.",
  rh08: "N'attends pas le redémarrage parfait. Prends l'imparfait.",
  rh09: "Reviens dans le jeu. Le banc n'est pas ta place.",
  rh10: "Récupère pour de vrai, puis reviens à fond.",
  rh11: "Les erreurs se paient en actes, pas en culpabilité.",
  rh12: "La remontée commence par le prochain petit geste.",
  rh13: "Pas de drame. Reset, et on y va.",
  rh14: "Womp womp. Au suivant.",
};
