import type { QuoteTexts } from "./types";

export const it: QuoteTexts = {
  // discipline · soft
  ds01: "Anche i piccoli passi ti portano avanti.",
  ds02: "Non serve aspettare il momento giusto: inizia piano.",
  ds03: "Fare un po' oggi vale più che progettare tanto.",
  ds04: "La costanza è un regalo per chi sarai domani.",
  ds05: "Un'ora di concentrazione può cambiare la forma di una giornata.",
  ds06: "Mantieni la promessa di stamattina, anche se è piccola.",
  ds07: "La disciplina può essere silenziosa: semplicemente, si ripresenta.",
  ds08: "Comincia dal passo più facile: lo slancio farà il resto.",
  ds09: "Si può andare piano e arrivare lontano.",
  ds10: "Finisci una cosa prima di iniziarne un'altra.",
  ds11: "Un piano chiaro rende più leggere le cose difficili.",
  ds12: "Oggi conta, anche se non è perfetto.",
  ds13: "Proteggi la tua attenzione: è lì che vive la tua giornata.",
  ds14: "Crea qualcosa.",
  ds15: "Inizia e basta: il resto lo capirai strada facendo.",
  ds16: "Non avere fretta nella salita.",
  ds17: "Forse non succederà in una notte, ma se molli non succederà affatto.",
  ds18: "Si tratta solo di essere intenzionali su ciò che vuoi.",
  ds19: "Realizza i tuoi sogni. Con affetto, GetControl.",
  ds20: "Abbiamo appena cominciato.",
  ds21: "Esisti per creare.",
  ds22: "Quando l'entusiasmo supera di poco la paura, è il momento di iniziare.",
  ds23: "Le possibilità sono infinite.",
  // discipline · direct
  dd01: "La motivazione va e viene. Fallo lo stesso.",
  dd02: "Decidi una volta sola, poi smetti di rimetterlo in discussione.",
  dd03: "Metti giù il telefono e inizia.",
  dd04: "Un piano funziona solo se ti muovi.",
  dd05: "Dieci minuti adesso valgono più di un'ora \"prima o poi\".",
  dd06: "Fatto è meglio di perfetto. Chiudilo.",
  dd07: "La tua agenda mostra le tue priorità. Controllala.",
  dd08: "Smetti di aspettare l'umore giusto. Inizia il lavoro.",
  dd09: "Fai prima la cosa difficile, finché hai energia.",
  dd10: "Se richiede due minuti, fallo adesso.",
  dd11: "Oggi di' di no a qualcosa, per dire sì a ciò che conta.",
  dd12: "Le scuse sono facili. I risultati vogliono ripetizioni.",
  dd13: "Scegli una priorità e difendila.",
  dd14: "Bisogna farlo succedere.",
  dd15: "Il piano B è solo il piano A con più tempo.",
  dd16: "Sognare e agire sono due cose diverse.",
  dd17: "Non aspettare la fortuna: costruiscitela.",
  dd18: "Se lo vuoi così tanto, trova un modo. Io mi fido di te.",
  dd19: "Il trucco è disciplina e costanza.",
  dd20: "Finisci quello che hai iniziato.",
  dd21: "Fai in modo che il tuo tempo valga molto.",
  dd22: "Il tempo non si rimborsa. Usalo con intenzione.",
  dd23: "Comportati come se ce l'avessi già.",
  dd24: "Se non ora, quando?",
  dd25: "Il prossimo tiro conta più dell'ultimo errore.",
  dd26: "Se qualcuno ce l'ha, perché tu no?",
  dd27: "Credi nei tuoi obiettivi in modo esagerato.",
  dd28: "Non essere tu l'ostacolo al tuo scopo.",
  dd29: "Tutto ciò che vuoi è dall'altra parte della paura.",
  dd30: "La prontezza ce l'hai dentro da sempre.",
  // discipline · hard
  dh01: "Nessuno verrà a farlo al posto tuo.",
  dh02: "Hai detto che l'avresti fatto. Allora fallo.",
  dh03: "Comodità oggi, rimpianto domani. Scegli.",
  dh04: "Niente scuse. Non oggi.",
  dh05: "L'orologio non aspetta il tuo umore. Al lavoro.",
  dh06: "Volerlo non basta. Guadagnatelo.",
  dh07: "Smetti di scorrere. Inizia a fare.",
  dh08: "Ogni rinvio è una scelta. Fanne una migliore.",
  dh09: "Il lavoro batte le chiacchiere. Ogni singola volta.",
  dh10: "Sai esattamente cosa fare. Vai.",
  dh11: "Disciplina adesso, o delusione dopo.",
  dh12: "\"Domani\" è il posto dove muoiono i progetti. Agisci oggi.",
  dh13: "Il lavoro non si fa da solo. Il cambiamento nemmeno.",
  dh14: "Fino in fondo.",
  dh15: "I grandi sogni chiedono grandi sacrifici.",
  dh16: "O aumenti il sacrificio, o riduci il desiderio.",
  dh17: "Gioca per vincere.",
  dh18: "Incassa così tante sconfitte che le vittorie non ti sorprenderanno più.",
  dh19: "Manifestare non serve. Agisci.",
  dh20: "Nel caso peggiore ce la fai. Nel migliore, ce la fai in grande.",
  dh21: "Non sei qui per una vita nella media.",
  dh22: "Per avere ciò che non hai mai avuto, fai ciò che non hai mai fatto.",
  dh23: "Nemmeno il cielo ti limita. Punta più in alto.",
  dh24: "Più sali sulla montagna, più il sentiero è insidioso.",
  dh25: "Vinci anche quando non si può vincere.",
  dh26: "La verità è che nessuno verrà a salvarti.",
  dh27: "Se nessuno ride dei tuoi obiettivi, sono troppo piccoli.",
  dh28: "Il mondo fa onde. Cavalcale o affonda: decidi tu.",
  dh29: "Nessun rischio, nessuna ricompensa.",
  // habits · soft
  hs01: "Un'abitudine è una scelta ripetuta con gentilezza.",
  hs02: "Rendila così piccola da non poterle dire di no.",
  hs03: "Stessa ora, stesso posto: lascia che la routine ti porti.",
  hs04: "Saltare una volta è umano. Tornare è l'abitudine.",
  hs05: "Festeggia le piccole vittorie: costruiscono quelle grandi.",
  hs06: "L'ambiente può fare metà del lavoro: preparalo.",
  hs07: "Lega una nuova abitudine a qualcosa che fai già.",
  hs08: "Un progresso che puoi ripetere vale più di uno che non puoi.",
  hs09: "Stasera prepara una cosa per domani mattina.",
  hs10: "Le abitudini crescono in silenzio, come le piante. Continua ad annaffiare.",
  hs11: "Una buona abitudine rende più facile la successiva.",
  hs12: "Nota cosa fai col pilota automatico. Scegli una cosa da migliorare.",
  hs13: "Comincia da dove sei, con quello che hai.",
  hs14: "Passeggiata mattutina?",
  hs15: "Prenditi del tempo per pensare.",
  hs16: "Cerca la conoscenza.",
  hs17: "Passa più tempo a conoscerti e meno ad assorbire chi ti sta intorno.",
  hs18: "Provarci è già un atto di cambiamento.",
  // habits · direct
  hd01: "Le tue giornate sono fatte di abitudini. Costruiscine di migliori.",
  hd02: "Mai saltare due volte di fila.",
  hd03: "Tienine traccia, o finirai per raccontarti storie.",
  hd04: "Rendi facile la scelta giusta.",
  hd05: "Togli un innesco dell'abitudine che vuoi lasciare.",
  hd06: "La ripetizione batte l'intensità.",
  hd07: "Se non è in agenda, è solo un desiderio.",
  hd08: "Piccole azioni ogni giorno, grandi risultati in un anno.",
  hd09: "Giornata storta? Fai la versione minima. Conta lo stesso.",
  hd10: "Anche il telefono è un'abitudine. Decidi chi comanda.",
  hd11: "Prima ci si presenta, poi si migliora.",
  hd12: "Accumula piccole vittorie prima di mezzogiorno.",
  hd13: "Diventi ciò che ripeti.",
  hd14: "Concentrati, per te.",
  hd15: "Evolvi o ripeti.",
  hd16: "Spezza lo schema.",
  hd17: "Lo slancio corregge gli errori più in fretta del rimpianto.",
  hd18: "Non agire d'impulso.",
  hd19: "Il modo più veloce per uccidere un'idea è chiedere a dieci persone cosa ne pensano.",
  hd20: "La vita non è fatta per stare fermi. Muoviti, sempre.",
  hd21: "Se la legna te la tagli da te, ti scalda due volte.",
  hd22: "Uff, odio le cose noiose. Tu no?",
  // habits · hard
  hh01: "Le tue abitudini votano per il tuo futuro. Controlla lo spoglio.",
  hh02: "Ogni \"solo per questa volta\" è un'abitudine travestita.",
  hh03: "Non ti manca il tempo. Ti manca una routine.",
  hh04: "Interrompi la serie delle scuse, non quella del lavoro.",
  hh05: "Stesse abitudini, stessi risultati. Cambia qualcosa.",
  hh06: "Basta rimandare la sveglia. Vinci il primo minuto.",
  hh07: "Due giorni saltati sono l'inizio della resa. Riprendi oggi.",
  hh08: "L'abitudine che stai evitando è quella che ti serve.",
  hh09: "Smetti di ricominciare da capo. Vai avanti.",
  hh10: "Se continui a farlo, lo stai scegliendo.",
  hh11: "La routine non è noiosa. Il caos costa caro.",
  hh12: "Elimina la distrazione. Oggi, non domani.",
  hh13: "Le buone intenzioni senza abitudini sono solo rumore.",
  hh14: "Conosci il prossimo passo. Speri solo che ce ne sia uno più facile.",
  // character · soft
  cs01: "Gentilezza e forza possono stare insieme.",
  cs02: "Mantieni le piccole promesse con te: diventano fiducia.",
  cs03: "Puoi avere pazienza con te e puntare in alto.",
  cs04: "L'onestà comincia da ciò che racconti a te.",
  cs05: "Fai la cosa giusta anche quando nessuno guarda.",
  cs06: "Il coraggio spesso è un sommesso \"ci riprovo\".",
  cs07: "I tuoi valori sono una bussola. Guardala oggi.",
  cs08: "Oggi ascolta più di quanto parli.",
  cs09: "La gratitudine rende sufficiente anche l'ordinario.",
  cs10: "Chiedere aiuto va bene. Anche quella è forza.",
  cs11: "Trattare gli altri con cura dà forma a chi diventi.",
  cs12: "L'impegno merita orgoglio, non solo il risultato.",
  cs13: "Cresci al tuo ritmo. Il confronto non è una mappa.",
  cs14: "Qual è la tua filosofia, esattamente?",
  cs15: "Come i soldi, anche le emozioni sono un investimento.",
  cs16: "Dentro sei di più.",
  cs17: "Credere in te non costa nulla. La fiducia è gratis.",
  cs18: "Il progetto parte dal credere in te.",
  cs19: "Sii un mistero.",
  cs20: "La vita è lo specchio della mente.",
  cs21: "Vestiti semplice, per te, non per fare colpo.",
  cs22: "Abbi il coraggio di fare male una cosa nuova.",
  cs23: "Cos'ha l'amore che ci fa perdere la testa?",
  // character · direct
  cd01: "Il carattere è ciò che fai quando è scomodo.",
  cd02: "Riconosci i tuoi errori. Poi rimediali.",
  cd03: "Di' ciò che pensi. Fai ciò che dici.",
  cd04: "Il rispetto si guadagna nei piccoli momenti.",
  cd05: "Arriva puntuale: dice agli altri che contano.",
  cd06: "Quando giusto e comodo non coincidono, scegli il giusto.",
  cd07: "Lamentarsi non cambia nulla. Agire sì.",
  cd08: "La tua parola è un contratto. Rispettala.",
  cd09: "Diventa la persona di cui i tuoi progetti hanno bisogno.",
  cd10: "Ammetti ciò che non sai. Poi imparalo.",
  cd11: "La calma è un'abilità. Allenala oggi.",
  cd12: "Chiarezza senza durezza, fermezza senza freddezza.",
  cd13: "Integrità è fare bene quando le scorciatoie sono facili.",
  cd14: "Non raccontare a nessuno i tuoi sogni.",
  cd15: "Appartieni a te, e solo a te.",
  cd16: "Fidati più dei fatti che delle parole.",
  cd17: "Arrabbiarsi va bene. Essere crudeli, mai.",
  cd18: "Le scelte fatte con rabbia non si possono annullare.",
  cd19: "La prima vittima della tua rabbia sei tu.",
  cd20: "Hai sbagliato? Chiedi scusa.",
  cd21: "Ti manca qualcuno? Diglielo.",
  cd22: "Provi amore? Dillo.",
  cd23: "Non farti desiderare: si vive una volta sola.",
  cd24: "Se serve, dissenti: è la tua opinione.",
  cd25: "Cura il carattere, non la reputazione: il primo è chi sei, la seconda è cosa pensano gli altri.",
  cd26: "Fidati dell'istinto.",
  cd27: "A volte devi fidarti della tua testa più di chiunque intorno a te.",
  cd28: "Credi all'antipatia a prima vista come credi all'amore a prima vista.",
  cd29: "Non tutti vedranno la tua visione. Vai avanti.",
  cd30: "Non serve crederci per avere il permesso di provarci.",
  cd31: "L'azione cura la paura.",
  // character · hard
  ch01: "Smetti di dare la colpa. Prenditi la responsabilità.",
  ch02: "Le parole costano poco. Dimostralo.",
  ch03: "Se ci tieni, dimostralo oggi.",
  ch04: "Nessuno ti deve una scorciatoia.",
  ch05: "Domanda onesta: hai da fare o stai evitando qualcosa?",
  ch06: "Le scuse non cambiano i risultati.",
  ch07: "Mantieni la parola, soprattutto con te.",
  ch08: "La paura può votare, ma non ha diritto di veto.",
  ch09: "Non aspettare il coraggio: agisci, e arriverà.",
  ch10: "Alza l'asticella. Poi restaci.",
  ch11: "La responsabilità non è un fardello. È potere.",
  ch12: "Smetti di chiederti se è giusto. Chiediti qual è la prossima mossa.",
  ch13: "Sotto pressione si vede chi sei. Preparati adesso.",
  ch14: "Che pensino quello che diavolo vogliono.",
  ch15: "Le critiche? Non sono un tuo problema.",
  ch16: "Non temere la brutta figura. Sii te.",
  ch17: "Pubblica, e non avere paura di cosa pensano gli altri.",
  ch18: "La verità è che non ti serve niente da nessuno.",
  ch19: "Se non ti riconoscono, vuol dire che stai facendo progressi.",
  ch20: "Non hanno idea di chi diventerai.",
  ch21: "Sei la tua paura peggiore e il tuo sogno migliore.",
  ch22: "Puoi viaggiare ovunque nel mondo, ma non puoi scappare da te.",
  ch23: "In una stanza piena di specchi, intorno a te vedresti solo vincenti.",
  ch24: "Fai le tue scelte e non voltarti indietro.",
  ch25: "Assicurati solo di elevarti sopra tutta questa follia.",
  ch26: "Gli uccelli nati in gabbia pensano che volare sia una malattia.",
  ch27: "Le persone intelligenti sanno cosa sono.",
  ch28: "Scegli il tuo scandalo e il tuo successo.",
  ch29: "Senza offesa, ma wow.",
  ch30: "Gne gne.",
  ch31: "Il bello del buon senso? È così… comune.",
  // recovery · soft
  rs01: "Il riposo fa parte del lavoro, non è una pausa dal lavoro.",
  rs02: "Anche in una giornata lenta, ci sei. Ed è abbastanza.",
  rs03: "Espira. Non devi fare tutto oggi.",
  rs04: "Gli inciampi fanno parte del percorso, non ne sono la fine.",
  rs05: "Stanotte dormi bene. Domani ti ringrazierà.",
  rs06: "Sii gentile con te come lo saresti con una persona cara.",
  rs07: "Fermarsi va bene. Ricordati solo di tornare.",
  rs08: "Oggi l'obiettivo è recuperare. Si può.",
  rs09: "Fai due passi, guarda il cielo, riparti.",
  rs10: "Hai già superato giornate difficili. Supererai anche questa.",
  rs11: "Lascia andare ieri. Oggi è una pagina nuova.",
  rs12: "Ripartire non è un fallimento. È manutenzione.",
  rs13: "Minuti di quiete: così torna l'energia.",
  rs14: "Prenditi il tempo di guarire.",
  rs15: "La gioia ha l'abitudine di tornare.",
  rs16: "Avrà senso più avanti.",
  rs17: "Lascia che succeda.",
  rs18: "Lascia entrare la luce.",
  rs19: "Un giorno, in qualche modo.",
  rs20: "Anche ciò che è rotto lascia passare la luce.",
  rs21: "Un passo indietro fa comunque parte della danza.",
  rs22: "Perdere qualcosa non è sempre una perdita.",
  rs23: "A volte bene, a volte male. Le cose vengono e vanno.",
  rs24: "Non dimenticare che anche tu fai parte della natura.",
  rs25: "Anche le persone possono essere musei, piene di storia che non possono più toccare.",
  rs26: "Puoi essere qualsiasi cosa, fare qualsiasi cosa, ricominciare.",
  rs27: "Va bene lasciare ciò che non ti fa stare bene, anche se è tutto ciò che hai sempre conosciuto.",
  rs28: "Fallo per te, e per tutte le notti in cui avevi solo te.",
  rs29: "Se vuoi pace, cercala con te o con chi la pensa come te.",
  rs30: "Evviva, urrà, ciao, grazie!",
  rs31: "Boh, è l'ora dell'eccetera.",
  rs32: "Buona notte, e bevi un po' d'acqua.",
  // recovery · direct
  rd01: "Uno scivolone. Va bene. Prossimo passo.",
  rd02: "Riposa per scelta, non perché crolli.",
  rd03: "Hai perso un giorno? Non perdere la settimana.",
  rd04: "Prima recupera, poi torna. In quest'ordine.",
  rd05: "I momenti storti non fanno una vita storta.",
  rd06: "Tieni la lezione, lascia il senso di colpa.",
  rd07: "Stasera spegni lo schermo un'ora prima.",
  rd08: "La pausa è uno strumento. Usala, poi torna.",
  rd09: "Piano saltato? Fanne uno più piccolo e rispettalo.",
  rd10: "Tutto fermo? Cambia una cosa, poi guarda di nuovo.",
  rd11: "La stanchezza è un'informazione, non una scusa.",
  rd12: "Riparti oggi. Non lunedì.",
  rd13: "Troppo da fare? Scrivi il prossimo minuscolo passo.",
  rd14: "A volte l'unico progresso è non arrendersi.",
  rd15: "Meno ti preoccupi, più vivi.",
  rd16: "Vivere bene è la migliore vendetta.",
  rd17: "Impara a goderti la vita senza bisogno di pubblico.",
  rd18: "Tutto ciò che si perde si può ritrovare, tranne il tempo sprecato.",
  rd19: "Una mentalità positiva fa una differenza, non la differenza.",
  rd20: "La libertà arriva quando capisci che la gabbia è fatta di pensieri.",
  rd21: "Sparisci per un po' e torna con più slancio.",
  rd22: "Non guardare indietro: non stai andando da quella parte.",
  rd23: "Il passato non è più nelle tue mani. Il futuro sì.",
  rd24: "Sii un po' egoista con il tuo tempo.",
  // recovery · hard
  rh01: "Cadi, ti rialzi. Senza discorsi.",
  rh02: "Commiserarsi spreca il tempo che serve per riprendersi.",
  rh03: "Ieri è finito. Smetti di rivederlo.",
  rh04: "Un giorno storto è un caso. Due sono una scelta.",
  rh05: "Riposare sì. Nascondersi no.",
  rh06: "Hai già ricominciato altre volte. Rifallo, adesso.",
  rh07: "Battuta d'arresto? Bene. Ora sai cosa sistemare.",
  rh08: "Non aspettare la ripartenza perfetta. Prendi quella imperfetta.",
  rh09: "Torna in campo. La panchina non è il tuo posto.",
  rh10: "Recupera davvero, poi torna a pieno ritmo.",
  rh11: "Gli errori si pagano con i fatti, non con i sensi di colpa.",
  rh12: "La rimonta comincia dalla prossima piccola mossa.",
  rh13: "Niente drammi. Reset e via.",
  rh14: "Womp womp. Avanti il prossimo.",
};
