import type { QuoteTexts } from "./types";

// In polacco il passato e gli aggettivi rivolti a "ty" hanno il genere
// (zrobiłeś/zrobiłaś, gotowy/gotowa): qui si usano presente, futuro e imperativo.
export const pl: QuoteTexts = {
  // discipline · soft
  ds01: "Małe kroki też prowadzą do przodu.",
  ds02: "Nie musisz czekać na idealny moment. Zacznij spokojnie.",
  ds03: "Zrobić dziś trochę to więcej niż dużo planować.",
  ds04: "Systematyczność to prezent dla osoby, którą będziesz jutro.",
  ds05: "Jedna godzina skupienia może zmienić kształt dnia.",
  ds06: "Dotrzymaj porannej obietnicy, nawet jeśli jest mała.",
  ds07: "Dyscyplina może być cicha. Po prostu znów się pojawia.",
  ds08: "Zacznij od najłatwiejszego kroku. Rozpęd zrobi resztę.",
  ds09: "Można iść powoli i zajść daleko.",
  ds10: "Skończ jedną rzecz, zanim zaczniesz następną.",
  ds11: "Jasny plan sprawia, że trudne rzeczy są lżejsze.",
  ds12: "Dziś się liczy, nawet jeśli nie jest idealnie.",
  ds13: "Chroń swoją uwagę: to w niej mieszka twój dzień.",
  ds14: "Stwórz coś.",
  ds15: "Po prostu zacznij. Resztę ogarniesz po drodze.",
  ds16: "Nie spiesz się na podejściu.",
  ds17: "Może nie stanie się to z dnia na dzień, ale jeśli odpuścisz, nie stanie się wcale.",
  ds18: "Chodzi tylko o to, żeby wiedzieć, czego chcesz.",
  ds19: "Spełniaj marzenia. Z sercem, GetControl.",
  ds20: "Dopiero zaczynamy.",
  ds21: "Istniejesz po to, by tworzyć.",
  ds22: "Gdy ekscytacja choć trochę przewyższa strach, wtedy zaczynasz.",
  ds23: "Możliwości są nieskończone.",
  // discipline · direct
  dd01: "Motywacja przychodzi i odchodzi. Zrób to mimo wszystko.",
  dd02: "Zdecyduj raz i przestań do tego wracać.",
  dd03: "Odłóż telefon i zacznij.",
  dd04: "Plan działa tylko wtedy, gdy ty działasz.",
  dd05: "Dziesięć minut teraz to więcej niż godzina „kiedyś”.",
  dd06: "Zrobione jest lepsze niż idealne. Zamknij to.",
  dd07: "Twój kalendarz pokazuje twoje priorytety. Sprawdź go.",
  dd08: "Przestań czekać na nastrój. Weź się do pracy.",
  dd09: "Najpierw zrób to, co trudne, póki masz energię.",
  dd10: "Jeśli to zajmuje dwie minuty, zrób to teraz.",
  dd11: "Powiedz dziś czemuś „nie”, żeby móc powiedzieć „tak” temu, co ważne.",
  dd12: "Wymówki są łatwe. Wyniki wymagają powtórzeń.",
  dd13: "Wybierz jeden priorytet i go broń.",
  dd14: "Trzeba to zrobić.",
  dd15: "Plan B to tylko plan A z większą ilością czasu.",
  dd16: "Marzyć i działać to dwie różne rzeczy.",
  dd17: "Nie czekaj na szczęście. Wypracuj je.",
  dd18: "Jeśli tak bardzo tego chcesz, znajdź sposób. Wierzę w ciebie.",
  dd19: "Kod do gry to dyscyplina i systematyczność.",
  dd20: "Dokończ to, co zaczęte.",
  dd21: "Zadbaj, żeby twój czas był dużo wart.",
  dd22: "Czasu nikt nie zwraca. Używaj go z rozmysłem.",
  dd23: "Działaj tak, jakby to już było twoje.",
  dd24: "Jeśli nie teraz, to kiedy?",
  dd25: "Następny rzut liczy się bardziej niż ostatni błąd.",
  dd26: "Jeśli ktoś to ma, czemu nie ty?",
  dd27: "Wierz w swoje cele ponad miarę.",
  dd28: "Nie stój na drodze własnemu celowi.",
  dd29: "Wszystko, czego chcesz, jest po drugiej stronie strachu.",
  dd30: "Masz w sobie wszystko od urodzenia.",
  // discipline · hard
  dh01: "Nikt nie przyjdzie zrobić tego za ciebie.",
  dh02: "Padło słowo, że to zrobisz. Więc zrób.",
  dh03: "Wygoda dziś, żal jutro. Wybieraj.",
  dh04: "Bez wymówek. Nie dziś.",
  dh05: "Zegar nie czeka na twój nastrój. Do roboty.",
  dh06: "Samo chcenie nie wystarczy. Zasłuż na to.",
  dh07: "Przestań scrollować. Zacznij działać.",
  dh08: "Każda zwłoka to decyzja. Podejmij lepszą.",
  dh09: "Praca wygrywa z gadaniem. Za każdym razem.",
  dh10: "Dokładnie wiesz, co robić. Jazda.",
  dh11: "Dyscyplina teraz albo rozczarowanie później.",
  dh12: "„Jutro” to miejsce, gdzie umierają plany. Działaj dziś.",
  dh13: "Praca sama się nie zrobi. Zmiana też nie.",
  dh14: "Na całość.",
  dh15: "Wielkie marzenia wymagają wielkich poświęceń.",
  dh16: "Albo zwiększ poświęcenie, albo zmniejsz pragnienie.",
  dh17: "Graj, żeby wygrać.",
  dh18: "Przyjmij tyle porażek, aż zwycięstwa przestaną cię dziwić.",
  dh19: "Manifestowanie nic nie daje. Działaj.",
  dh20: "W najgorszym razie ci się uda. W najlepszym uda ci się na wielką skalę.",
  dh21: "Nie jesteś tu po przeciętność.",
  dh22: "Żeby mieć to, czego jeszcze nie masz, rób to, czego jeszcze nie robisz.",
  dh23: "Nawet niebo cię nie ogranicza. Celuj wyżej.",
  dh24: "Im wyżej na górze, tym zdradliwsza ścieżka.",
  dh25: "Wygraj w sytuacji bez wyjścia.",
  dh26: "Prawda jest taka: nikt nie przyjdzie cię ratować.",
  dh27: "Jeśli nikt nie śmieje się z twoich celów, są za małe.",
  dh28: "Świat robi fale. Surfuj albo toń: twój wybór.",
  dh29: "Bez ryzyka nie ma nagrody.",
  // habits · soft
  hs01: "Nawyk to wybór, który powtarzasz z życzliwością.",
  hs02: "Zrób to tak małe, że nie da się odmówić.",
  hs03: "Ta sama pora, to samo miejsce: niech rutyna cię niesie.",
  hs04: "Opuścić raz to ludzka rzecz. Wracać to nawyk.",
  hs05: "Świętuj małe wygrane: budują te wielkie.",
  hs06: "Otoczenie może zrobić połowę pracy. Przygotuj je.",
  hs07: "Przypnij nowy nawyk do czegoś, co już robisz.",
  hs08: "Postęp, który da się powtórzyć, wygrywa z takim, którego się nie da.",
  hs09: "Dziś wieczorem przygotuj jedną rzecz na jutrzejszy poranek.",
  hs10: "Nawyki rosną po cichu, jak rośliny. Podlewaj dalej.",
  hs11: "Jeden dobry nawyk ułatwia następny.",
  hs12: "Zauważ, co robisz na autopilocie. Wybierz jedną rzecz do poprawy.",
  hs13: "Zacznij tam, gdzie jesteś, z tym, co masz.",
  hs14: "Poranny spacer?",
  hs15: "Daj sobie czas do namysłu.",
  hs16: "Szukaj wiedzy.",
  hs17: "Więcej czasu na poznawanie siebie, mniej na chłonięcie wszystkich dookoła.",
  hs18: "Próbowanie to już zmiana.",
  // habits · direct
  hd01: "Twoje dni są zbudowane z nawyków. Buduj lepsze dni.",
  hd02: "Nigdy nie opuszczaj dwa razy z rzędu.",
  hd03: "Zapisuj, bo inaczej zaczniesz opowiadać sobie bajki.",
  hd04: "Spraw, żeby dobry wybór był tym łatwym.",
  hd05: "Usuń jeden wyzwalacz nawyku, który chcesz rzucić.",
  hd06: "Powtarzalność wygrywa z intensywnością.",
  hd07: "Jeśli tego nie ma w kalendarzu, to tylko życzenie.",
  hd08: "Małe działania codziennie, duże wyniki w rok.",
  hd09: "Kiepski dzień? Zrób wersję minimum. To też się liczy.",
  hd10: "Telefon to też nawyk. Zdecyduj, kto tu rządzi.",
  hd11: "Najpierw się pojaw. Potem się poprawiaj.",
  hd12: "Zbieraj małe wygrane przed południem.",
  hd13: "Stajesz się tym, co powtarzasz.",
  hd14: "Skup się, dla siebie.",
  hd15: "Ewoluuj albo powtarzaj.",
  hd16: "Przełam schemat.",
  hd17: "Rozpęd poprawia błędy szybciej niż żal.",
  hd18: "Nie działaj pod wpływem impulsu.",
  hd19: "Najszybszy sposób na zabicie pomysłu to zapytać dziesięć osób, co o nim myślą.",
  hd20: "Życie nie jest po to, by stać w miejscu. Ruszaj się, zawsze.",
  hd21: "Drewno porąbane własnymi rękami grzeje dwa razy.",
  hd22: "Ugh, nienawidzę nudnych rzeczy. A ty nie?",
  // habits · hard
  hh01: "Twoje nawyki głosują na twoją przyszłość. Sprawdź wyniki.",
  hh02: "Każde „tylko ten jeden raz” to przebrany nawyk.",
  hh03: "Nie brakuje ci czasu. Brakuje ci rutyny.",
  hh04: "Przerwij serię wymówek, nie serię pracy.",
  hh05: "Te same nawyki, te same wyniki. Zmień coś.",
  hh06: "Przestań odkładać budzik. Wygraj pierwszą minutę.",
  hh07: "Dwa opuszczone dni to początek rezygnacji. Wróć dziś.",
  hh08: "Nawyk, którego unikasz, to ten, którego potrzebujesz.",
  hh09: "Przestań zaczynać od zera. Idź dalej.",
  hh10: "Jeśli dalej to robisz, to to wybierasz.",
  hh11: "Rutyna nie jest nudna. Chaos jest drogi.",
  hh12: "Usuń rozpraszacz. Dziś, nie jutro.",
  hh13: "Dobre chęci bez nawyków to tylko hałas.",
  hh14: "Znasz swój następny krok. Liczysz tylko na łatwiejszy.",
  // character · soft
  cs01: "Życzliwość i siła mogą iść w parze.",
  cs02: "Dotrzymuj małych obietnic wobec siebie. Zamieniają się w zaufanie.",
  cs03: "Możesz mieć do siebie cierpliwość i nadal celować wysoko.",
  cs04: "Uczciwość zaczyna się od tego, co mówisz sobie.",
  cs05: "Rób to, co słuszne, nawet gdy nikt nie patrzy.",
  cs06: "Odwaga to często ciche „spróbuję jeszcze raz”.",
  cs07: "Twoje wartości to kompas. Zerknij na niego dziś.",
  cs08: "Dziś więcej słuchaj, niż mów.",
  cs09: "Wdzięczność sprawia, że zwyczajność wystarcza.",
  cs10: "Prosić o pomoc to nic złego. To też siła.",
  cs11: "To, jak traktujesz innych, kształtuje to, kim się stajesz.",
  cs12: "Wysiłek zasługuje na dumę, nie tylko wynik.",
  cs13: "Rośnij we własnym tempie. Porównywanie to nie mapa.",
  cs14: "Jaka jest właściwie twoja filozofia?",
  cs15: "Tak jak pieniądze, emocje też są inwestycją.",
  cs16: "W środku jesteś czymś więcej.",
  cs17: "Wiara w siebie nic nie kosztuje. Pewność siebie jest za darmo.",
  cs18: "Plan zaczyna się od wiary w siebie.",
  cs19: "Bądź zagadką.",
  cs20: "Życie to lustro umysłu.",
  cs21: "Ubieraj się prosto, dla siebie, nie żeby zaimponować.",
  cs22: "Miej odwagę robić coś nowego źle.",
  cs23: "Co takiego jest w miłości, że tracimy dla niej głowę?",
  // character · direct
  cd01: "Charakter to to, co robisz, kiedy jest niewygodnie.",
  cd02: "Przyznaj się do błędów. Potem je napraw.",
  cd03: "Mów, co myślisz. Rób, co mówisz.",
  cd04: "Szacunek zdobywa się w małych chwilach.",
  cd05: "Bądź na czas: to mówi innym, że się liczą.",
  cd06: "Gdy słuszne i wygodne się rozchodzą, wybierz słuszne.",
  cd07: "Narzekanie nic nie zmienia. Działanie tak.",
  cd08: "Twoje słowo to umowa. Dotrzymaj go.",
  cd09: "Stań się osobą, której potrzebują twoje plany.",
  cd10: "Przyznaj, czego nie wiesz. Potem się tego naucz.",
  cd11: "Spokój to umiejętność. Ćwicz go dziś.",
  cd12: "Jasność bez szorstkości, stanowczość bez chłodu.",
  cd13: "Uczciwość to robić dobrze, gdy skróty są łatwe.",
  cd14: "Nie opowiadaj nikomu o swoich marzeniach.",
  cd15: "Należysz do siebie i tylko do siebie.",
  cd16: "Ufaj czynom bardziej niż słowom.",
  cd17: "Złość jest w porządku. Okrucieństwo nigdy.",
  cd18: "Decyzji podjętych w złości nie da się cofnąć.",
  cd19: "Pierwszą ofiarą twojej złości jesteś ty.",
  cd20: "Błąd? Przeproś.",
  cd21: "Tęsknisz za kimś? Powiedz to.",
  cd22: "Kochasz? Mów o tym.",
  cd23: "Nie daj się prosić: żyje się raz.",
  cd24: "Nie zgadzaj się, jeśli trzeba. To twoje zdanie.",
  cd25: "Dbaj o charakter, nie o reputację: charakter to ty, reputacja to opinia innych.",
  cd26: "Ufaj intuicji.",
  cd27: "Czasem trzeba ufać własnej głowie bardziej niż komukolwiek wokół.",
  cd28: "Wierz w antypatię od pierwszego wejrzenia, jak wierzysz w miłość od pierwszego wejrzenia.",
  cd29: "Nie każdy zobaczy twoją wizję. Rób swoje.",
  cd30: "Nie trzeba w to wierzyć, żeby mieć prawo spróbować.",
  cd31: "Działanie leczy strach.",
  // character · hard
  ch01: "Przestań obwiniać. Weź odpowiedzialność.",
  ch02: "Gadać jest łatwo. Pokaż to.",
  ch03: "Jeśli ci zależy, udowodnij to dziś.",
  ch04: "Nikt nie jest ci winien skrótu.",
  ch05: "Szczere pytanie: masz dużo do zrobienia czy czegoś unikasz?",
  ch06: "Wymówki nie zmieniają wyników.",
  ch07: "Dotrzymuj słowa, zwłaszcza sobie.",
  ch08: "Strach ma głos, ale nie ma weta.",
  ch09: "Nie czekaj na odwagę. Działaj, a przyjdzie.",
  ch10: "Podnieś poprzeczkę. I tam zostań.",
  ch11: "Odpowiedzialność to nie ciężar. To moc.",
  ch12: "Przestań pytać, czy to sprawiedliwe. Zapytaj, co dalej.",
  ch13: "Presja pokazuje, kim jesteś. Przygotuj się teraz.",
  ch14: "Niech sobie myślą, co im się, do diabła, podoba.",
  ch15: "Krytyka? Nie twój problem.",
  ch16: "Nie bój się ośmieszenia. Bądź sobą.",
  ch17: "Opublikuj to i nie bój się, co pomyślą inni.",
  ch18: "Fakty są takie: od nikogo niczego nie potrzebujesz.",
  ch19: "Jeśli cię nie poznają, to znaczy, że robisz postępy.",
  ch20: "Nie mają pojęcia, kim się staniesz.",
  ch21: "Jesteś swoim najgorszym lękiem i najpiękniejszą fantazją.",
  ch22: "Możesz pojechać wszędzie na świecie, ale przed sobą nie uciekniesz.",
  ch23: "W pokoju pełnym luster otaczaliby cię sami zwycięzcy.",
  ch24: "Podejmuj decyzje i nie oglądaj się za siebie.",
  ch25: "Po prostu wznieś się ponad to całe szaleństwo.",
  ch26: "Ptaki urodzone w klatce myślą, że latanie to choroba.",
  ch27: "Mądrzy ludzie wiedzą, kim są.",
  ch28: "Wybierz swój skandal i swój sukces.",
  ch29: "Bez urazy, ale wow.",
  ch30: "Ble ble ble.",
  ch31: "Zdrowy rozsądek? Taki… zwyczajny.",
  // recovery · soft
  rs01: "Odpoczynek to część pracy, nie przerwa od niej.",
  rs02: "Nawet w powolny dzień jesteś tu. I to wystarczy.",
  rs03: "Zrób wydech. Nie musisz dziś zrobić wszystkiego.",
  rs04: "Potknięcia są częścią drogi, nie jej końcem.",
  rs05: "Wyśpij się dziś. Jutro ci podziękuje.",
  rs06: "Traktuj siebie tak łagodnie, jak kogoś, kogo kochasz.",
  rs07: "Pauza jest w porządku. Pamiętaj tylko, żeby wrócić.",
  rs08: "Dziś celem jest regeneracja. Wolno.",
  rs09: "Przejdź się chwilę, spójrz w niebo, zacznij od nowa.",
  rs10: "Trudne dni już bywały. Ten też przetrwasz.",
  rs11: "Puść wczoraj. Dziś to nowa strona.",
  rs12: "Restart to nie porażka. To konserwacja.",
  rs13: "Spokojne minuty to sposób, w jaki wraca energia.",
  rs14: "Daj sobie czas, żeby się zagoić.",
  rs15: "Radość ma zwyczaj wracać.",
  rs16: "Później to nabierze sensu.",
  rs17: "Pozwól temu się stać.",
  rs18: "Wpuść światło.",
  rs19: "Kiedyś, jakoś.",
  rs20: "Nawet to, co pęknięte, przepuszcza światło.",
  rs21: "Krok w tył to też część tańca.",
  rs22: "Stracić coś to nie zawsze strata.",
  rs23: "Czasem dobrze, czasem źle. Rzeczy przychodzą i odchodzą.",
  rs24: "Nie zapominaj, że ty też jesteś częścią natury.",
  rs25: "Ludzie też bywają muzeami, pełnymi historii, której nie mogą już dotknąć.",
  rs26: "Możesz być kimkolwiek, robić cokolwiek, zacząć od nowa.",
  rs27: "W porządku jest zostawić to, co nie służy, nawet jeśli to wszystko, co znasz.",
  rs28: "Zrób to dla siebie i dla wszystkich samotnych nocy.",
  rs29: "Jeśli chcesz spokoju, szukaj go w sobie albo u kogoś, kto myśli jak ty.",
  rs30: "Hura, juhu, pa, dzięki!",
  rs31: "Nie wiem, czas na et cetera.",
  rs32: "Dobranoc i pij wodę.",
  // recovery · direct
  rd01: "Poślizg. Okej. Następny krok.",
  rd02: "Odpoczywaj z wyboru, nie z wyczerpania.",
  rd03: "Stracony dzień? Nie trać tygodnia.",
  rd04: "Najpierw regeneracja, potem powrót. W tej kolejności.",
  rd05: "Złe chwile nie robią złego życia.",
  rd06: "Zatrzymaj lekcję, odpuść winę.",
  rd07: "Dziś wieczorem wyłącz ekran godzinę wcześniej.",
  rd08: "Przerwa to narzędzie. Użyj jej i wróć.",
  rd09: "Plan nie wyszedł? Zrób mniejszy i się go trzymaj.",
  rd10: "Wszystko stoi? Zmień jedną rzecz i spójrz jeszcze raz.",
  rd11: "Zmęczenie to informacja, nie wymówka.",
  rd12: "Zacznij od nowa dziś. Nie w poniedziałek.",
  rd13: "Za dużo na głowie? Zapisz następny malutki krok.",
  rd14: "Czasem jedyny postęp to się nie poddać.",
  rd15: "Im mniej się martwisz, tym bardziej żyjesz.",
  rd16: "Dobre życie to najlepsza zemsta.",
  rd17: "Naucz się cieszyć życiem bez potrzeby publiczności.",
  rd18: "Wszystko, co stracone, można odnaleźć, oprócz zmarnowanego czasu.",
  rd19: "Pozytywne nastawienie robi różnicę, ale nie całą.",
  rd20: "Wolność zaczyna się, gdy widzisz, że klatka jest z myśli.",
  rd21: "Zniknij na chwilę i wróć z większym rozpędem.",
  rd22: "Nie oglądaj się. Nie idziesz w tamtą stronę.",
  rd23: "Przeszłość nie jest już w twoich rękach. Przyszłość tak.",
  rd24: "Pilnuj swojego czasu trochę egoistycznie.",
  // recovery · hard
  rh01: "Upadasz, wstajesz. Bez przemówień.",
  rh02: "Użalanie się nad sobą marnuje czas potrzebny na powrót.",
  rh03: "Wczoraj się skończyło. Przestań je odtwarzać.",
  rh04: "Jeden zły dzień to przypadek. Dwa to wybór.",
  rh05: "Odpoczynek tak. Chowanie się nie.",
  rh06: "Zaczynanie od nowa już ci się zdarzało. Zrób to znowu, teraz.",
  rh07: "Porażka? Dobrze. Teraz wiesz, co naprawić.",
  rh08: "Nie czekaj na idealny restart. Bierz nieidealny.",
  rh09: "Wracaj do gry. Ławka to nie twoje miejsce.",
  rh10: "Zregeneruj się naprawdę, potem wróć na pełnych obrotach.",
  rh11: "Za błędy płaci się czynami, nie poczuciem winy.",
  rh12: "Powrót zaczyna się od następnego małego ruchu.",
  rh13: "Bez dramatów. Reset i jazda.",
  rh14: "Womp womp. Następny.",
};
