import type { QuoteTexts } from "./types";

// Portoghese del Brasile.
export const pt: QuoteTexts = {
  // discipline · soft
  ds01: "Passos pequenos também levam você adiante.",
  ds02: "Não precisa esperar o momento certo. Comece com calma.",
  ds03: "Fazer um pouco hoje vale mais do que planejar muito.",
  ds04: "A constância é um presente para quem você vai ser amanhã.",
  ds05: "Uma hora de foco pode mudar a forma de um dia.",
  ds06: "Cumpra a promessa desta manhã, mesmo que seja pequena.",
  ds07: "A disciplina pode ser silenciosa. Ela simplesmente aparece de novo.",
  ds08: "Comece pelo passo mais fácil. O embalo faz o resto.",
  ds09: "Dá para ir devagar e chegar longe.",
  ds10: "Termine uma coisa antes de começar a próxima.",
  ds11: "Um plano claro deixa as coisas difíceis mais leves.",
  ds12: "Hoje conta, mesmo que não seja perfeito.",
  ds13: "Proteja sua atenção: é nela que o seu dia vive.",
  ds14: "Crie algo.",
  ds15: "Só comece. Você descobre no caminho.",
  ds16: "Não tenha pressa na subida.",
  ds17: "Talvez não aconteça da noite para o dia, mas se você desistir, não vai acontecer nunca.",
  ds18: "É só ter clareza sobre o que você quer.",
  ds19: "Realize seus sonhos. Com carinho, GetControl.",
  ds20: "A gente só está começando.",
  ds21: "Você existe para criar.",
  ds22: "Quando a empolgação passa um pouco do medo, é hora de começar.",
  ds23: "As possibilidades são infinitas.",
  // discipline · direct
  dd01: "A motivação vem e vai. Faça mesmo assim.",
  dd02: "Decida uma vez e pare de reabrir a questão.",
  dd03: "Largue o celular e comece.",
  dd04: "Um plano só funciona se você se mexer.",
  dd05: "Dez minutos agora valem mais que uma hora \"algum dia\".",
  dd06: "Feito é melhor que perfeito. Finalize.",
  dd07: "Sua agenda mostra suas prioridades. Confira.",
  dd08: "Pare de esperar o humor certo. Comece o trabalho.",
  dd09: "Faça primeiro a coisa difícil, enquanto tem energia.",
  dd10: "Se leva dois minutos, faça agora.",
  dd11: "Diga não a algo hoje, para dizer sim ao que importa.",
  dd12: "Desculpas são fáceis. Resultados pedem repetição.",
  dd13: "Escolha uma prioridade e defenda.",
  dd14: "Tem que acontecer.",
  dd15: "O plano B é só o plano A com mais tempo.",
  dd16: "Sonhar e agir são duas coisas diferentes.",
  dd17: "Não espere ter sorte. Faça a sua sorte.",
  dd18: "Se você quer tanto, encontre um jeito. Eu confio em você.",
  dd19: "O atalho secreto é disciplina e constância.",
  dd20: "Termine o que você começou.",
  dd21: "Faça o seu tempo valer muito.",
  dd22: "Tempo não tem reembolso. Use com intenção.",
  dd23: "Aja como se já tivesse.",
  dd24: "Se não for agora, quando?",
  dd25: "O próximo arremesso importa mais que o último erro.",
  dd26: "Se alguém tem, por que você não?",
  dd27: "Acredite nos seus objetivos de um jeito exagerado.",
  dd28: "Não seja o obstáculo do seu próprio propósito.",
  dd29: "Tudo o que você quer está do outro lado do medo.",
  dd30: "Você já nasceu com tudo o que precisa.",
  // discipline · hard
  dh01: "Ninguém vai vir fazer isso por você.",
  dh02: "Você disse que faria. Então faça.",
  dh03: "Conforto hoje, arrependimento amanhã. Escolha.",
  dh04: "Sem desculpas. Hoje não.",
  dh05: "O relógio não espera o seu humor. Ao trabalho.",
  dh06: "Querer não basta. Conquiste.",
  dh07: "Pare de rolar a tela. Comece a fazer.",
  dh08: "Cada adiamento é uma decisão. Tome uma melhor.",
  dh09: "Trabalho vence conversa. Toda vez.",
  dh10: "Você sabe exatamente o que fazer. Vai.",
  dh11: "Disciplina agora, ou decepção depois.",
  dh12: "\"Amanhã\" é onde os planos vão morrer. Aja hoje.",
  dh13: "O trabalho não se faz sozinho. A mudança também não.",
  dh14: "Com tudo.",
  dh15: "Grandes sonhos pedem grandes sacrifícios.",
  dh16: "Ou aumente o sacrifício, ou diminua o desejo.",
  dh17: "Jogue para ganhar.",
  dh18: "Acumule tantas derrotas que as vitórias nem surpreendam mais.",
  dh19: "Manifestar não adianta. Aja.",
  dh20: "Na pior das hipóteses, você consegue. Na melhor, consegue em grande.",
  dh21: "Você não está aqui para uma vida mediana.",
  dh22: "Para ter o que nunca teve, faça o que nunca fez.",
  dh23: "Nem o céu limita você. Mire mais alto.",
  dh24: "Quanto mais alto na montanha, mais traiçoeiro o caminho.",
  dh25: "Vença na situação impossível.",
  dh26: "A verdade é que ninguém vem salvar você.",
  dh27: "Se ninguém ri dos seus objetivos, eles são pequenos demais.",
  dh28: "O mundo faz ondas. Surfe ou afunde: você decide.",
  dh29: "Sem risco, sem recompensa.",
  // habits · soft
  hs01: "Um hábito é uma escolha que você repete com gentileza.",
  hs02: "Deixe tão pequeno que não dê para dizer não.",
  hs03: "Mesma hora, mesmo lugar: deixe a rotina levar você.",
  hs04: "Falhar uma vez é humano. Voltar é o hábito.",
  hs05: "Comemore as pequenas vitórias: elas constroem as grandes.",
  hs06: "O ambiente pode fazer metade do trabalho. Prepare-o.",
  hs07: "Amarre um hábito novo a algo que você já faz.",
  hs08: "Um progresso que dá para repetir vale mais do que um que não dá.",
  hs09: "Hoje à noite, prepare uma coisa para amanhã de manhã.",
  hs10: "Hábitos crescem em silêncio, como plantas. Continue regando.",
  hs11: "Um bom hábito facilita o próximo.",
  hs12: "Repare no que você faz no piloto automático. Escolha uma coisa para melhorar.",
  hs13: "Comece de onde você está, com o que você tem.",
  hs14: "Caminhada de manhã?",
  hs15: "Tire um tempo para pensar.",
  hs16: "Busque conhecimento.",
  hs17: "Passe mais tempo se conhecendo e menos absorvendo todo mundo ao redor.",
  hs18: "Tentar já é um ato de mudança.",
  // habits · direct
  hd01: "Seus dias são feitos de hábitos. Construa dias melhores.",
  hd02: "Nunca pule duas vezes seguidas.",
  hd03: "Anote, ou você vai acabar se contando histórias.",
  hd04: "Faça da escolha certa a escolha fácil.",
  hd05: "Tire um gatilho do hábito que você quer largar.",
  hd06: "Repetição vence intensidade.",
  hd07: "Se não está na agenda, é só um desejo.",
  hd08: "Pequenas ações todo dia, grandes resultados em um ano.",
  hd09: "Dia ruim? Faça a versão mínima. Conta do mesmo jeito.",
  hd10: "O celular também é um hábito. Decida quem manda.",
  hd11: "Primeiro apareça. Depois melhore.",
  hd12: "Junte pequenas vitórias antes do meio-dia.",
  hd13: "Você se torna o que repete.",
  hd14: "Foco, por você.",
  hd15: "Evolua ou repita.",
  hd16: "Quebre o padrão.",
  hd17: "O embalo corrige erros mais rápido que o arrependimento.",
  hd18: "Não aja por impulso.",
  hd19: "O jeito mais rápido de matar uma ideia é perguntar a dez pessoas o que elas acham.",
  hd20: "A vida não foi feita para ficar parada. Mexa-se, sempre.",
  hd21: "Se você corta a própria lenha, ela aquece duas vezes.",
  hd22: "Argh, odeio coisas chatas. Você não?",
  // habits · hard
  hh01: "Seus hábitos votam no seu futuro. Confira a contagem.",
  hh02: "Todo \"só desta vez\" é um hábito disfarçado.",
  hh03: "Não falta tempo. Falta rotina.",
  hh04: "Quebre a sequência de desculpas, não a de trabalho.",
  hh05: "Mesmos hábitos, mesmos resultados. Mude alguma coisa.",
  hh06: "Pare de adiar o despertador. Ganhe o primeiro minuto.",
  hh07: "Dois dias pulados são o começo da desistência. Volte hoje.",
  hh08: "O hábito que você está evitando é o que você precisa.",
  hh09: "Pare de recomeçar do zero. Continue.",
  hh10: "Se você continua fazendo, está escolhendo.",
  hh11: "Rotina não é chata. Caos custa caro.",
  hh12: "Elimine a distração. Hoje, não amanhã.",
  hh13: "Boas intenções sem hábitos são só barulho.",
  hh14: "Você conhece o próximo passo. Só está torcendo por um mais fácil.",
  // character · soft
  cs01: "Gentileza e força podem andar juntas.",
  cs02: "Cumpra as pequenas promessas que faz a si: elas viram confiança.",
  cs03: "Dá para ter paciência consigo e mirar alto.",
  cs04: "A honestidade começa pelo que você conta a si.",
  cs05: "Faça o certo, mesmo quando ninguém está olhando.",
  cs06: "Coragem muitas vezes é um \"vou tentar de novo\" baixinho.",
  cs07: "Seus valores são uma bússola. Olhe para ela hoje.",
  cs08: "Hoje, escute mais do que fala.",
  cs09: "A gratidão faz o comum parecer suficiente.",
  cs10: "Pedir ajuda tudo bem. Isso também é força.",
  cs11: "Tratar os outros com cuidado molda quem você se torna.",
  cs12: "O esforço merece orgulho, não só o resultado.",
  cs13: "Cresça no seu ritmo. Comparação não é mapa.",
  cs14: "Qual é a sua filosofia, exatamente?",
  cs15: "Assim como o dinheiro, as emoções também são um investimento.",
  cs16: "Por dentro, você é mais.",
  cs17: "Acreditar em si não custa nada. Confiança é de graça.",
  cs18: "O projeto começa por acreditar em si.",
  cs19: "Seja um mistério.",
  cs20: "A vida é um espelho da mente.",
  cs21: "Vista-se de forma simples, para você, não para impressionar.",
  cs22: "Tenha coragem de fazer mal uma coisa nova.",
  cs23: "O que o amor tem que faz a gente perder a cabeça?",
  // character · direct
  cd01: "Caráter é o que você faz quando não é conveniente.",
  cd02: "Assuma seus erros. Depois conserte.",
  cd03: "Diga o que pensa. Faça o que diz.",
  cd04: "Respeito se conquista nos pequenos momentos.",
  cd05: "Chegue na hora: isso diz aos outros que eles importam.",
  cd06: "Quando o certo e o fácil se separam, escolha o certo.",
  cd07: "Reclamar não muda nada. Agir muda.",
  cd08: "Sua palavra é um contrato. Honre.",
  cd09: "Torne-se a pessoa de que seus planos precisam.",
  cd10: "Admita o que não sabe. Depois aprenda.",
  cd11: "Calma é uma habilidade. Pratique hoje.",
  cd12: "Clareza sem dureza, firmeza sem frieza.",
  cd13: "Integridade é fazer certo quando os atalhos são fáceis.",
  cd14: "Não conte seus sonhos a ninguém.",
  cd15: "Você pertence a você, e só a você.",
  cd16: "Confie mais em atitudes do que em palavras.",
  cd17: "Sentir raiva, tudo bem. Ser cruel, nunca.",
  cd18: "Escolhas feitas com raiva não se desfazem.",
  cd19: "A primeira vítima da sua raiva é você.",
  cd20: "Errou? Peça desculpas.",
  cd21: "Saudade de alguém? Fale.",
  cd22: "Amando? Diga.",
  cd23: "Não se faça de difícil: só se vive uma vez.",
  cd24: "Discorde se precisar: é a sua opinião.",
  cd25: "Cuide do seu caráter, não da reputação: um é quem você é, a outra é o que pensam de você.",
  cd26: "Confie no seu instinto.",
  cd27: "Às vezes você precisa confiar na sua cabeça mais do que em qualquer pessoa ao redor.",
  cd28: "Acredite na antipatia à primeira vista como acredita no amor à primeira vista.",
  cd29: "Nem todo mundo vai enxergar a sua visão. Siga em frente.",
  cd30: "Não precisa acreditar para ter permissão de tentar.",
  cd31: "Ação cura o medo.",
  // character · hard
  ch01: "Pare de culpar. Assuma.",
  ch02: "Falar é fácil. Mostre.",
  ch03: "Se importa para você, prove hoje.",
  ch04: "Ninguém te deve um atalho.",
  ch05: "Pergunta sincera: você está sem tempo ou está fugindo de algo?",
  ch06: "Desculpas não mudam resultados.",
  ch07: "Cumpra sua palavra, principalmente com você.",
  ch08: "O medo tem voto, não veto.",
  ch09: "Não espere a coragem. Aja, e ela vem.",
  ch10: "Suba a régua. Depois fique lá.",
  ch11: "Responsabilidade não é um fardo. É poder.",
  ch12: "Pare de perguntar se é justo. Pergunte o que vem agora.",
  ch13: "A pressão mostra quem você é. Prepare-se agora.",
  ch14: "Deixa pensarem o que quiserem, que se dane.",
  ch15: "Críticas? Não é problema seu.",
  ch16: "Pague mico. Seja você.",
  ch17: "Poste, e não tenha medo do que os outros pensam.",
  ch18: "A verdade é que você não precisa de nada de ninguém.",
  ch19: "Se não reconhecem você, é sinal de que está progredindo.",
  ch20: "Eles não fazem ideia de quem você vai se tornar.",
  ch21: "Você é o seu pior medo e a sua melhor fantasia.",
  ch22: "Você pode viajar para qualquer lugar do mundo, mas não pode fugir de si.",
  ch23: "Numa sala cheia de espelhos, você só veria vencedores.",
  ch24: "Faça escolhas e não olhe para trás.",
  ch25: "Só garanta que você vai se erguer acima de toda essa loucura.",
  ch26: "Pássaros nascidos na gaiola acham que voar é doença.",
  ch27: "Gente inteligente sabe o que é.",
  ch28: "Escolha o seu escândalo e o seu sucesso.",
  ch29: "Sem ofensa, mas uau.",
  ch30: "Nhenhenhém.",
  ch31: "O senso comum? É tão… comum.",
  // recovery · soft
  rs01: "Descanso faz parte do trabalho, não é uma pausa dele.",
  rs02: "Mesmo num dia lento, você está aqui. E isso basta.",
  rs03: "Solte o ar. Você não precisa fazer tudo hoje.",
  rs04: "Tropeços fazem parte do caminho, não são o fim dele.",
  rs05: "Durma bem hoje. O amanhã vai agradecer.",
  rs06: "Trate-se com a gentileza que teria com alguém que você ama.",
  rs07: "Tudo bem fazer uma pausa. Só lembre de voltar.",
  rs08: "Hoje o objetivo é se recuperar. Pode.",
  rs09: "Dê uma volta curta, olhe o céu, recomece.",
  rs10: "Você já passou por dias difíceis. Vai passar por este.",
  rs11: "Deixe o ontem ir. Hoje é uma página nova.",
  rs12: "Recomeçar não é fracassar. É manutenção.",
  rs13: "Minutos de calma são o jeito de a energia voltar.",
  rs14: "Tire um tempo para se curar.",
  rs15: "A alegria tem o hábito de voltar.",
  rs16: "Vai fazer sentido depois.",
  rs17: "Deixa acontecer.",
  rs18: "Deixe a luz entrar.",
  rs19: "Algum dia, de algum jeito.",
  rs20: "Até o que está quebrado deixa a luz passar.",
  rs21: "Um passo para trás ainda faz parte da dança.",
  rs22: "Perder algo nem sempre é uma perda.",
  rs23: "Às vezes bem, às vezes mal. As coisas vêm e vão.",
  rs24: "Não esqueça que você também faz parte da natureza.",
  rs25: "Pessoas também podem ser museus, cheias de história que já não podem tocar.",
  rs26: "Você pode ser qualquer coisa, fazer qualquer coisa, recomeçar.",
  rs27: "Tudo bem deixar para trás o que não faz bem, mesmo que seja tudo o que você conheceu.",
  rs28: "Faça por você, e por todas as noites em que você só tinha você.",
  rs29: "Se quer paz, busque consigo ou com alguém que pensa como você.",
  rs30: "Eba, viva, tchau, valeu!",
  rs31: "Sei lá, hora do etcétera.",
  rs32: "Boa noite, e beba água.",
  // recovery · direct
  rd01: "Um escorregão. Tudo bem. Próximo passo.",
  rd02: "Descanse por escolha, não por desabar.",
  rd03: "Perdeu um dia? Não perca a semana.",
  rd04: "Recupere-se, depois volte. Nessa ordem.",
  rd05: "Momentos ruins não fazem uma vida ruim.",
  rd06: "Fique com a lição, largue a culpa.",
  rd07: "Hoje à noite, desligue a tela uma hora antes.",
  rd08: "Uma pausa é uma ferramenta. Use e depois volte.",
  rd09: "Perdeu o plano? Faça um menor e cumpra.",
  rd10: "Tudo travado? Mude uma coisa e olhe de novo.",
  rd11: "Cansaço é informação, não desculpa.",
  rd12: "Recomece hoje. Não na segunda.",
  rd13: "Muita coisa para fazer? Anote o próximo passo minúsculo.",
  rd14: "Às vezes o único progresso é não desistir.",
  rd15: "Quanto menos você se preocupa, mais você vive.",
  rd16: "Viver bem é a melhor vingança.",
  rd17: "Aprenda a curtir a vida sem precisar de plateia.",
  rd18: "Tudo o que se perde pode ser achado, menos o tempo desperdiçado.",
  rd19: "Uma mente positiva faz uma diferença, não toda a diferença.",
  rd20: "A liberdade começa quando você percebe que a gaiola é feita de pensamentos.",
  rd21: "Suma por um tempo e volte com mais embalo.",
  rd22: "Não olhe para trás: você não vai para lá.",
  rd23: "O passado não está mais nas suas mãos. O futuro, sim.",
  rd24: "Seja um pouco egoísta com o seu tempo.",
  // recovery · hard
  rh01: "Cai, levanta. Sem discurso.",
  rh02: "Ter pena de si desperdiça o tempo que você precisa para se recuperar.",
  rh03: "Ontem acabou. Pare de reprisar.",
  rh04: "Um dia ruim é um acaso. Dois são uma escolha.",
  rh05: "Descansar, sim. Se esconder, não.",
  rh06: "Você já recomeçou outras vezes. Faça de novo, agora.",
  rh07: "Revés? Ótimo. Agora você sabe o que consertar.",
  rh08: "Não espere o recomeço perfeito. Pegue o imperfeito.",
  rh09: "Volte para o jogo. O banco não é o seu lugar.",
  rh10: "Recupere-se de verdade, depois volte com força total.",
  rh11: "Erros se pagam com atitude, não com culpa.",
  rh12: "A virada começa com o próximo pequeno movimento.",
  rh13: "Sem drama. Reinicia e vai.",
  rh14: "Womp womp. Próximo.",
};
